[package]
id = "refactor"
version = "0.11.0"
name = "Refactor"
status = "ready"

[family]
default = "quick"

[family.variant]

[family.variant.quick]
path = "generated/quick/index.toml"
aliases = ["refactor-quick"]

[family.variant.guided]
path = "generated/guided/index.toml"
aliases = ["refactor-guided"]

[family.variant.complex]
path = "generated/complex/index.toml"
aliases = ["refactor-complex"]

[publish]
name = "@ctx-traits/refactor"
access = "public"
