// Generated by `ctx traits sdk-generate` from Rust SDK vocabulary.
// Do not edit by hand.

export type JsonValue = null | boolean | number | string | readonly JsonValue[] | JsonObject;
export type JsonObject = { readonly [key: string]: JsonValue | undefined };

export type RefKind = "agent" | "condition" | "port" | "prompt" | "resource" | "rule" | "schema" | "sequence" | "session" | "signal" | "slot" | "trait";
export type SchemaBuiltin = "schema:text" | "schema:boolean" | "schema:number" | "schema:integer" | "schema:any";
export type SchemaForm = SchemaBuiltin | `[${string}]` | `(${string})`;
export const schemaForms = {
  list: { prefix: "[", separator: "", suffix: "]" },
  union: { prefix: "(", separator: "|", suffix: ")" },
} as const;
export type WriteOperation = "replace" | "append" | "merge" | { readonly "set-field": string } | "increment";
export type SynthFormat = "toml" | "json" | "yaml";
export type RuntimeSurface = "wasm-core" | "wasm-plugin" | "cli-json";
export type RuntimeOperation = "validate" | "normalize" | "synth" | "audit" | "import-plan" | "render" | "compose" | "resolve" | "explain" | "pack" | "cache-plan" | "ledger-update";

/** Built-in ToneBuiltIn values.
 * @property technical Use precise implementation and API terminology.
 * @property direct State conclusions plainly and label blockers without softening them.
 * @property warm Use warm and respectful language.
 * @property formal Use a formal professional tone.
 * @property calm Stay calm and measured.
 * @property critical Inspect claims critically.
 * @property encouraging Encourage progress while preserving accuracy.
 * @property curious Ask clarifying questions when evidence is insufficient.
 */
export type ToneBuiltIn = "technical" | "direct" | "warm" | "formal" | "calm" | "critical" | "encouraging" | "curious";
export const Tone = {
  /** Use precise implementation and API terminology. Name concrete types, contracts, boundaries, validation paths, and runtime effects when they are relevant. */
  technical: "technical",
  /** State conclusions plainly and label blockers without softening them. Be respectful, but do not bury critical findings behind hedging or praise. */
  direct: "direct",
  /** Use warm and respectful language. Keep feedback human and constructive without hiding risks or required repairs. */
  warm: "warm",
  /** Use a formal professional tone. Prefer precise phrasing, complete sentences, and stable terminology over casual idioms. */
  formal: "formal",
  /** Stay calm and measured. Describe risks and blockers without alarmism, blame, or exaggerated certainty. */
  calm: "calm",
  /** Inspect claims critically. Look for correctness, safety, trust, and evidence gaps before accepting the happy path. */
  critical: "critical",
  /** Encourage progress while preserving accuracy. Acknowledge useful direction when relevant, but do not let encouragement replace concrete findings. */
  encouraging: "encouraging",
  /** Ask clarifying questions when evidence is insufficient. Prefer targeted questions about unknowns over guessing intent or inventing missing context. */
  curious: "curious",
} as const satisfies Record<string, ToneBuiltIn>;

/** Built-in MethodBuiltIn values.
 * @property evidence-first Ground every finding in observed evidence.
 * @property socratic Use questions to guide reasoning when appropriate.
 * @property options-first Present viable options before recommending one.
 * @property critique-first Lead with critique and risks.
 * @property first-principles Reason from first principles.
 * @property divergent Explore multiple plausible directions.
 * @property convergent Converge on a specific recommendation.
 */
export type MethodBuiltIn = "evidence-first" | "socratic" | "options-first" | "critique-first" | "first-principles" | "divergent" | "convergent";
export const Method = {
  /** Ground every finding in observed evidence. Cite source, command, artifact, or report evidence when available. If evidence is incomplete, state the uncertainty. */
  evidenceFirst: "evidence-first",
  /** Use questions to guide reasoning when appropriate. Ask focused questions that expose assumptions or tradeoffs instead of lecturing through every answer. */
  socratic: "socratic",
  /** Present viable options before recommending one. Name tradeoffs clearly so the user can choose or confirm the preferred path. */
  optionsFirst: "options-first",
  /** Lead with critique and risks. Identify material issues before praise, summaries, or broad suggestions. */
  critiqueFirst: "critique-first",
  /** Reason from first principles. Explain the underlying constraint or invariant before applying local conventions. */
  firstPrinciples: "first-principles",
  /** Explore multiple plausible directions. Generate distinct approaches and tradeoffs before narrowing the answer. */
  divergent: "divergent",
  /** Converge on a specific recommendation. Reduce options to the smallest defensible next step when enough evidence is available. */
  convergent: "convergent",
} as const satisfies Record<string, MethodBuiltIn>;

/** Built-in VerbosityBuiltIn values.
 * @property brief Keep output compact unless risk explanation needs detail.
 * @property terse Use the shortest useful answer.
 * @property normal Use normal concise detail.
 * @property detailed Use detailed explanations when they improve correctness.
 */
export type VerbosityBuiltIn = "brief" | "terse" | "normal" | "detailed";
export const Verbosity = {
  /** Keep output compact unless risk explanation needs detail. Avoid long generic explanations. Expand only when needed to explain impact or a minimal repair. */
  brief: "brief",
  /** Use the shortest useful answer. Omit nonessential commentary and preserve only the facts or actions needed for the task. */
  terse: "terse",
  /** Use normal concise detail. Provide enough context to be actionable without expanding into exhaustive background. */
  normal: "normal",
  /** Use detailed explanations when they improve correctness. Include rationale, evidence, and edge cases when the user needs them to trust or apply the answer. */
  detailed: "detailed",
} as const satisfies Record<string, VerbosityBuiltIn>;

/** Built-in FormatBuiltIn values.
 * @property bullets Use bullet lists for scanability.
 * @property table Use tables when comparison is clearer.
 * @property checklist Use checklist form for verification work.
 * @property findings-first Put material findings before general commentary.
 * @property answer-first Answer directly before explaining.
 * @property questions-first Start with necessary questions.
 * @property steps Use ordered steps for procedures.
 */
export type FormatBuiltIn = "bullets" | "table" | "checklist" | "findings-first" | "answer-first" | "questions-first" | "steps";
export const Format = {
  /** Use bullet lists for scanability. Group related facts into concise bullets without nesting unnecessary hierarchy. */
  bullets: "bullets",
  /** Use tables when comparison is clearer. Prefer tables for parallel options, statuses, fields, or tradeoff matrices. */
  table: "table",
  /** Use checklist form for verification work. Make each item concrete, observable, and independently confirmable. */
  checklist: "checklist",
  /** Put material findings before general commentary. Order findings by severity, then list residual risks and validation gaps separately. */
  findingsFirst: "findings-first",
  /** Answer directly before explaining. Lead with the conclusion or requested value, then include caveats and supporting detail. */
  answerFirst: "answer-first",
  /** Start with necessary questions. Ask only questions that block a correct answer or materially change the recommendation. */
  questionsFirst: "questions-first",
  /** Use ordered steps for procedures. Sequence actions in the order they should be performed and keep each step actionable. */
  steps: "steps",
} as const satisfies Record<string, FormatBuiltIn>;

/** Built-in DirectnessBuiltIn values.
 * @property low Use low directness.
 * @property medium Use medium directness.
 * @property high Do not hedge material blockers.
 */
export type DirectnessBuiltIn = "low" | "medium" | "high";
export const Directness = {
  /** Use low directness. Soften phrasing when user context benefits from tact, while preserving correctness and caveats. */
  low: "low",
  /** Use medium directness. State issues plainly while keeping tone balanced and collaborative. */
  medium: "medium",
  /** Do not hedge material blockers. Use clear blocker language for correctness, safety, or trust risks. */
  high: "high",
} as const satisfies Record<string, DirectnessBuiltIn>;

/** Built-in ScopeControlBuiltIn values.
 * @property strict Stay inside the requested scope.
 * @property moderate Allow limited adjacent scope when it reduces risk.
 * @property expansive Consider broader context when useful.
 */
export type ScopeControlBuiltIn = "strict" | "moderate" | "expansive";
export const ScopeControl = {
  /** Stay inside the requested scope. Avoid broad rewrites, unrelated style preferences, and speculative architecture advice outside the active task. */
  strict: "strict",
  /** Allow limited adjacent scope when it reduces risk. Mention nearby issues only when they affect the requested work or validation confidence. */
  moderate: "moderate",
  /** Consider broader context when useful. Surface adjacent risks, alternatives, or follow-up work when they materially improve the outcome. */
  expansive: "expansive",
} as const satisfies Record<string, ScopeControlBuiltIn>;

/** Built-in InitiativeBuiltIn values.
 * @property wait-for-instruction Wait for explicit instruction before acting.
 * @property ask-before-expanding-scope Ask before expanding scope.
 * @property suggest-next-steps Suggest focused next steps.
 * @property proactively-execute-safe-steps Proactively execute safe requested work.
 */
export type InitiativeBuiltIn = "wait-for-instruction" | "ask-before-expanding-scope" | "suggest-next-steps" | "proactively-execute-safe-steps";
export const Initiative = {
  /** Wait for explicit instruction before acting. Do not start implementation or extra investigation unless the user asks for it. */
  waitForInstruction: "wait-for-instruction",
  /** Ask before expanding scope. Pause for confirmation before taking on adjacent work beyond the requested task. */
  askBeforeExpandingScope: "ask-before-expanding-scope",
  /** Suggest focused next steps. Offer concise follow-up actions without performing them unless asked or already authorized. */
  suggestNextSteps: "suggest-next-steps",
  /** Proactively execute safe requested work. Carry through low-risk implementation and verification steps when they are clearly part of the task. */
  proactivelyExecuteSafeSteps: "proactively-execute-safe-steps",
} as const satisfies Record<string, InitiativeBuiltIn>;

/** Built-in UncertaintyBuiltIn values.
 * @property ask-when-blocked Ask when blocked by missing information.
 * @property state-assumptions State assumptions explicitly.
 * @property list-unknowns List important unknowns.
 * @property refuse-to-guess Refuse to guess when evidence is required.
 */
export type UncertaintyBuiltIn = "ask-when-blocked" | "state-assumptions" | "list-unknowns" | "refuse-to-guess";
export const Uncertainty = {
  /** Ask when blocked by missing information. Stop and request the specific missing decision or access needed rather than guessing. */
  askWhenBlocked: "ask-when-blocked",
  /** State assumptions explicitly. Call out assumptions that affect the answer, implementation, or validation result. */
  stateAssumptions: "state-assumptions",
  /** List important unknowns. Separate known evidence from unresolved facts that could change the conclusion. */
  listUnknowns: "list-unknowns",
  /** Refuse to guess when evidence is required. Say what evidence is missing and avoid inventing facts, validation results, or behavior. */
  refuseToGuess: "refuse-to-guess",
} as const satisfies Record<string, UncertaintyBuiltIn>;

/** Built-in IntentRequireBuiltIn values.
 * @property inspect-changed-behavior Inspect the changed behavior before giving conclusions.
 * @property report-actionable-finding Report actionable findings.
 * @property verify-coverage Check whether changed behavior is covered.
 * @property state-assumptions State assumptions explicitly when required context is missing.
 * @property preserve-scope Stay within the requested task unless the user approves expanding scope.
 * @property leanness Keep the implementation lean.
 * @property reuse-over-reimplement Reuse existing behavior before reimplementing it.
 * @property review-before-final Review the work before presenting it as final.
 * @property gates-green-before-commit Require the relevant validation gates to pass before committing.
 * @property bounded-refinement Refine through a bounded review-and-repair loop.
 * @property role-attributed-output Attribute output to the role that produced or reviewed it.
 * @property robustness Prefer changes that remain correct under ordinary failure and boundary conditions.
 * @property pragmatism Choose the smallest practical change that satisfies the phase contract.
 * @property elegance Favor clear, cohesive designs over clever or incidental complexity.
 * @property behavior-preserving-default Preserve observed behavior unless the phase explicitly changes it.
 * @property verbatim-execution Execute the agreed draft exactly as written and record departures.
 * @property annotation-fidelity Turn every annotation into one checklist item without dropping or merging it.
 */
export type IntentRequireBuiltIn = "inspect-changed-behavior" | "report-actionable-finding" | "verify-coverage" | "state-assumptions" | "preserve-scope" | "leanness" | "reuse-over-reimplement" | "review-before-final" | "gates-green-before-commit" | "bounded-refinement" | "role-attributed-output" | "robustness" | "pragmatism" | "elegance" | "behavior-preserving-default" | "verbatim-execution" | "annotation-fidelity";
/** Built-in IntentFocusBuiltIn values.
 * @property correctness Prioritize correctness and observable behavior over style preferences.
 * @property tests Pay attention to test coverage and assertions.
 * @property specific Prefer specific, actionable observations over general advice.
 * @property security Look for security-sensitive behavior.
 * @property performance Call out meaningful performance regressions.
 * @property maintainability Notice complexity, coupling, and brittle structure.
 * @property data-loss Watch for behavior that can delete, corrupt, overwrite, leak, or make user data unreachable.
 * @property user-impact Tie findings and recommendations to user-visible impact when possible.
 */
export type IntentFocusBuiltIn = "correctness" | "tests" | "specific" | "security" | "performance" | "maintainability" | "data-loss" | "user-impact";
/** Built-in IntentAvoidBuiltIn values.
 * @property style-only Do not produce style-only feedback unless the user explicitly asks for style review.
 * @property scope-creep Do not expand beyond the requested task.
 * @property big-rewrite Do not propose or perform a large rewrite unless it is necessary for the requested outcome.
 * @property unrequested-refactor Do not refactor code that is outside the requested change.
 * @property speculative-claim Do not present guesses as facts.
 * @property unbounded-loop Do not continue refinement without a defined stop condition.
 * @property rubber-stamp-review Do not approve work without substantive review.
 * @property weaken-tests-to-pass Do not weaken tests merely to make a change pass.
 * @property taste-only-blocking Do not treat subjective taste as a blocking defect.
 * @property accretion Do not add code or complexity beside an existing solution without need.
 * @property over-engineering Do not build beyond the demonstrated need.
 * @property gold-plating Do not add unrequested polish or features.
 * @property duplication Do not duplicate logic that should be shared.
 * @property interface-widening Do not broaden public interfaces without a concrete caller need.
 * @property silent-deviation Do not silently adapt an unsatisfiable or contradicted plan.
 */
export type IntentAvoidBuiltIn = "style-only" | "scope-creep" | "big-rewrite" | "unrequested-refactor" | "speculative-claim" | "unbounded-loop" | "rubber-stamp-review" | "weaken-tests-to-pass" | "taste-only-blocking" | "accretion" | "over-engineering" | "gold-plating" | "duplication" | "interface-widening" | "silent-deviation";
/** Built-in IntentBlockBuiltIn values.
 * @property destructive-change Do not perform destructive changes without explicit approval.
 * @property secret-exfiltration Do not reveal, copy, upload, or move secrets or credentials.
 * @property unapproved-network Do not use network access unless the user or host policy explicitly allows it.
 * @property unsafe-command Do not suggest or run commands that can destroy data or alter system state without approval.
 * @property policy-bypass Do not bypass user, repository, host, or organization policy.
 */
export type IntentBlockBuiltIn = "destructive-change" | "secret-exfiltration" | "unapproved-network" | "unsafe-command" | "policy-bypass";
export type IntentBuiltIn = IntentRequireBuiltIn | IntentFocusBuiltIn | IntentAvoidBuiltIn | IntentBlockBuiltIn;

export const Intent = {
  require: {
    /** Inspect the changed behavior before giving conclusions. Read the relevant diff, nearby code, and tests when available before listing findings. */
    inspectChangedBehavior: "inspect-changed-behavior",
    /** Report actionable findings. Each finding should include what is wrong, why it matters, and where it appears when location data is available. */
    reportActionableFinding: "report-actionable-finding",
    /** Check whether changed behavior is covered. Look for tests, examples, or documented acceptance criteria for the change, and note a verification gap when none exists. */
    verifyCoverage: "verify-coverage",
    /** State assumptions explicitly when required context is missing. Make each assumption visible near the claim it supports instead of proceeding silently. */
    stateAssumptions: "state-assumptions",
    /** Stay within the requested task unless the user approves expanding scope. Mention unrelated cleanup or adjacent work as optional instead of doing it. */
    preserveScope: "preserve-scope",
    /** Keep the implementation lean. Add only what the requested outcome needs. */
    leanness: "leanness",
    /** Reuse existing behavior before reimplementing it. Extract shared logic instead of copying it beside the original. */
    reuseOverReimplement: "reuse-over-reimplement",
    /** Review the work before presenting it as final. Inspect the completed change against requirements before finalizing. */
    reviewBeforeFinal: "review-before-final",
    /** Require the relevant validation gates to pass before committing. Run applicable checks and resolve failures first. */
    gatesGreenBeforeCommit: "gates-green-before-commit",
    /** Refine through a bounded review-and-repair loop. Recheck material repairs, then stop at the acceptance condition. */
    boundedRefinement: "bounded-refinement",
    /** Attribute output to the role that produced or reviewed it. Label reviewer evidence separately from implementation output. */
    roleAttributedOutput: "role-attributed-output",
    /** Prefer changes that remain correct under ordinary failure and boundary conditions. Prefer changes that remain correct under ordinary failure and boundary conditions. */
    robustness: "robustness",
    /** Choose the smallest practical change that satisfies the phase contract. Choose the smallest practical change that satisfies the phase contract. */
    pragmatism: "pragmatism",
    /** Favor clear, cohesive designs over clever or incidental complexity. Favor clear, cohesive designs over clever or incidental complexity. */
    elegance: "elegance",
    /** Preserve observed behavior unless the phase explicitly changes it. Keep existing observable behavior intact unless the task explicitly requires a behavior change. */
    behaviorPreservingDefault: "behavior-preserving-default",
    /** Execute the agreed draft exactly as written and record departures. Follow the approved draft or design and explicitly report every necessary departure. */
    verbatimExecution: "verbatim-execution",
    /** Turn every annotation into one checklist item without dropping or merging it. Preserve each human annotation as exactly one actionable checklist item. */
    annotationFidelity: "annotation-fidelity",
  } as const satisfies Record<string, IntentRequireBuiltIn>,
  focus: {
    /** Prioritize correctness and observable behavior over style preferences. Prefer a real bug or behavior gap over naming or style feedback. */
    correctness: "correctness",
    /** Pay attention to test coverage and assertions. Notice missing assertions, uncovered branches, and tests that no longer match the intended behavior. */
    tests: "tests",
    /** Prefer specific, actionable observations over general advice. Name the affected behavior, artifact, or location when available. */
    specific: "specific",
    /** Look for security-sensitive behavior. Watch for permission issues, injection risks, and unsafe data exposure such as user-controlled input reaching a shell command. */
    security: "security",
    /** Call out meaningful performance regressions. Note avoidable expensive operations, such as an accidental quadratic loop over a large collection, when relevant to the task. */
    performance: "performance",
    /** Notice complexity, coupling, and brittle structure. Point out unclear naming and duplicated branching that would make future changes harder. */
    maintainability: "maintainability",
    /** Watch for behavior that can delete, corrupt, overwrite, leak, or make user data unreachable. Flag operations like a migration that drops a column before the data is copied. */
    dataLoss: "data-loss",
    /** Tie findings and recommendations to user-visible impact when possible. Explain, for example, that a bug can cause users to lose draft work. */
    userImpact: "user-impact",
  } as const satisfies Record<string, IntentFocusBuiltIn>,
  avoid: {
    /** Do not produce style-only feedback unless the user explicitly asks for style review. Skip cosmetic renames unless they affect correctness or clarity materially. */
    styleOnly: "style-only",
    /** Do not expand beyond the requested task. Ask before pursuing adjacent work rather than turning a review into a refactor. */
    scopeCreep: "scope-creep",
    /** Do not propose or perform a large rewrite unless it is necessary for the requested outcome. Prefer a narrow fix over rewriting the subsystem. */
    bigRewrite: "big-rewrite",
    /** Do not refactor code that is outside the requested change. Leave unrelated files untouched while addressing the requested work. */
    unrequestedRefactor: "unrequested-refactor",
    /** Do not present guesses as facts. Mark uncertainty clearly and say what would confirm a claim instead of asserting behavior. */
    speculativeClaim: "speculative-claim",
    /** Do not continue refinement without a defined stop condition. Bound repair cycles by acceptance criteria or an iteration limit. */
    unboundedLoop: "unbounded-loop",
    /** Do not approve work without substantive review. Check requirements and evidence before approving. */
    rubberStampReview: "rubber-stamp-review",
    /** Do not weaken tests merely to make a change pass. Repair the implementation unless the contract genuinely changed. */
    weakenTestsToPass: "weaken-tests-to-pass",
    /** Do not treat subjective taste as a blocking defect. Keep preferences advisory unless they expose a material risk. */
    tasteOnlyBlocking: "taste-only-blocking",
    /** Do not add code or complexity beside an existing solution without need. Consolidate related behavior rather than adding parallel helpers. */
    accretion: "accretion",
    /** Do not build beyond the demonstrated need. Avoid speculative generality and unsupported abstractions. */
    overEngineering: "over-engineering",
    /** Do not add unrequested polish or features. Deliver the requested outcome without optional enhancements. */
    goldPlating: "gold-plating",
    /** Do not duplicate logic that should be shared. Reuse or extract common behavior that should evolve together. */
    duplication: "duplication",
    /** Do not broaden public interfaces without a concrete caller need. Keep externally visible interfaces narrow unless a demonstrated caller requires expansion. */
    interfaceWidening: "interface-widening",
    /** Do not silently adapt an unsatisfiable or contradicted plan. Record and resolve deviations instead of making unreported changes to an agreed plan or design. */
    silentDeviation: "silent-deviation",
  } as const satisfies Record<string, IntentAvoidBuiltIn>,
  block: {
    /** Do not perform destructive changes without explicit approval. Refuse to delete data or rewrite history unless the user approves. */
    destructiveChange: "destructive-change",
    /** Do not reveal, copy, upload, or move secrets or credentials. Do not paste tokens, .env contents, or private keys into output. */
    secretExfiltration: "secret-exfiltration",
    /** Do not use network access unless the user or host policy explicitly allows it. Do not fetch and run a remote script without approval. */
    unapprovedNetwork: "unapproved-network",
    /** Do not suggest or run commands that can destroy data or alter system state without approval. Ask before running commands like rm -rf, git reset --hard, or destructive database commands. */
    unsafeCommand: "unsafe-command",
    /** Do not bypass user, repository, host, or organization policy. Do not work around permission prompts or repository rules. */
    policyBypass: "policy-bypass",
  } as const satisfies Record<string, IntentBlockBuiltIn>,
} as const;

export type AgentTemplateName = "worker" | "reviewer" | "planner" | "oracle" | "searcher";
export type AgentModelTier = "top" | "fast";

export interface AgentTemplateDefinition {
  readonly description: string;
  readonly summary: string;
  readonly modelTier?: AgentModelTier;
}

export const agentTemplates = {
  worker: { description: "Completes assigned work and produces the requested outputs.", summary: "Execution role." },
  reviewer: { description: "Reviews assigned work against its requirements and reports actionable findings.", summary: "Review role." },
  planner: { description: "Structures assigned work into a clear, actionable plan.", summary: "Planning role." },
  oracle: { description: "Provides high-quality consultation for difficult decisions without owning execution.", summary: "Top-tier consultation role.", modelTier: "top" },
  searcher: { description: "Retrieves and summarizes relevant information without modifying the workspace.", summary: "Fast read-only retrieval role.", modelTier: "fast" },
} as const satisfies Record<AgentTemplateName, AgentTemplateDefinition>;

export type ResourceTrigger = "on-activation" | "on-demand";
export const ResourceTrigger = {
  onActivation: "on-activation",
  onDemand: "on-demand",
} as const satisfies Record<string, ResourceTrigger>;

export type ResourceRoot = "package" | "repo";
export const ResourceRoot = {
  package: "package",
  repo: "repo",
} as const satisfies Record<string, ResourceRoot>;

export type ResourceRender = "reference" | "inline";
export const ResourceRender = {
  reference: "reference",
  inline: "inline",
} as const satisfies Record<string, ResourceRender>;

export type Status = "draft" | "ready";
export const Status = {
  draft: "draft",
  ready: "ready",
} as const satisfies Record<string, Status>;

export type Trust = "verified" | "blocked" | "unreviewed";
export const Trust = {
  verified: "verified",
  blocked: "blocked",
  unreviewed: "unreviewed",
} as const satisfies Record<string, Trust>;

export interface CdkDiagnostic {
  readonly severity: "warning" | "error";
  readonly code: string;
  readonly fieldPath: string;
  readonly message: string;
}

export interface SynthPlan {
  readonly delegate: "ctx-traits-wasm-core-or-cli";
  readonly command: readonly string[];
  readonly draft: JsonObject;
  readonly diagnostics: readonly CdkDiagnostic[];
  readonly format: SynthFormat;
  readonly out?: string;
}

export interface RuntimeDelegationPlan {
  readonly surface: RuntimeSurface;
  readonly operation: RuntimeOperation;
  readonly wasmExport?: string;
  readonly cliCommand?: readonly string[];
  readonly request: JsonValue;
  readonly note: "delegates-to-rust-core";
}
// --- Canonical document model (generated from the Rust trait schema) ---

/**
 * A portable abstract agent role declaration.
 */
export type CanonicalAgent = {
  /**
   * Required human-readable role description.
   */
  readonly "description": string;
  /**
   * Role identifier, referenced by sequence items as `agent:<id>`.
   */
  readonly "id": string;
  /**
   * Optional session binding for this agent's frames: `session:<id>`
   * (shared with every other agent bound to the same declared session),
   * or a bare `per-frame`/`persistent` lifecycle value, which is always
   * agent-local and never implies sharing. Omitted preserves legacy
   * configuration-driven behavior during migration; absent both canonical
   * and configured values remains `per-frame`.
   */
  readonly "session"?: string | undefined;
  /**
   * Optional short role summary.
   */
  readonly "summary"?: string | undefined;
  /**
   * Optional standing instructions for this role, delivered through the
   * harness's system-prompt channel once per session rather than repeated
   * in every frame's user message. Holds doctrine the role always obeys —
   * not per-step work, which belongs in the step's own prompt. Model-visible
   * like any other instruction text: compiled into the model view, audited
   * for hidden content, and covered by the canonical digest.
   */
  readonly "system"?: string | undefined;
};

/**
 * `[behavior]` model.
 */
export type CanonicalBehavior = {
  /**
   * Directness level: scalar slug.
   */
  readonly "directness"?: CanonicalGuidanceItem | undefined;
  /**
   * Format descriptors (e.g. "findings-first", "bullets").
   */
  readonly "format"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Initiative: scalar slug.
   */
  readonly "initiative"?: CanonicalGuidanceItem | undefined;
  /**
   * Method descriptors (e.g. "evidence-first").
   */
  readonly "method"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Scope control: scalar slug.
   */
  readonly "scope-control"?: CanonicalGuidanceItem | undefined;
  /**
   * Tone descriptors (e.g. "technical", "direct").
   */
  readonly "tone"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Uncertainty handling: scalar slug.
   */
  readonly "uncertainty"?: CanonicalGuidanceItem | undefined;
  /**
   * Verbosity level: scalar slug.
   */
  readonly "verbosity"?: CanonicalGuidanceItem | undefined;
};

/**
 * One ordered `branch-failure` entry naming a declared branch and its
 * terminal failure policy.
 */
export type CanonicalBranchFailureEntry = {
  readonly "branch": string;
  readonly "on-failure": CanonicalBranchFailurePolicy;
};

/**
 * Per-branch terminal failure policy.
 */
export type CanonicalBranchFailurePolicy = "skip" | "park" | "panel-fail";

/**
 * One declared checklist item: the unit that receives exactly one verdict.
 * 
 * `id` is the item's identity and is stable across rewordings of `text` — a
 * reworded criterion keeps its id and changes its digest, which is what lets
 * a receipt distinguish "this item was answered again" from "this item now
 * asks something else". Deriving an id from `text` would collapse that
 * distinction, so ids are declared, never computed.
 */
export type CanonicalChecklistItem = {
  /**
   * Elaboration presented alongside `text`. Detail is never separately
   * verdict-bearing: one item is one verdict.
   */
  readonly "detail"?: string | undefined;
  /**
   * Item identifier, unique within its checklist.
   */
  readonly "id": string;
  /**
   * Whether a verdict for this item must carry evidence. When any item in
   * a checklist requires it, the synthesized verdict schema makes the
   * `evidence` field required.
   */
  readonly "requires-evidence"?: boolean | undefined;
  /**
   * The criterion as the reviewer reads it.
   */
  readonly "text": string;
};

/**
 * Advanced command declaration table. The source shorthand `cmd = "..."`
 * remains the primary authoring path; this table carries explicit argv when
 * the author needs to avoid string parsing entirely.
 */
export type CanonicalCommandDeclaration = {
  /**
   * Explicit argv. Mutually exclusive with `argv-from`.
   */
  readonly "argv"?: readonly string[] | undefined;
  /**
   * Local `[schema:text]` input port resolved once into concrete argv when
   * the command frame is built. Slots are deliberately unsupported so an
   * agent-produced value cannot select the executable.
   */
  readonly "argv-from"?: string | undefined;
  /**
   * See [`CommandPlan::capture_bytes`].
   */
  readonly "capture-bytes"?: number | undefined;
  /**
   * Optional working directory policy.
   */
  readonly "cwd"?: string | undefined;
  readonly "executable-digest-from"?: string | undefined;
  /**
   * Runtime idle timeout in milliseconds.
   */
  readonly "idle-timeout-ms"?: number | undefined;
  /**
   * Exit codes treated as success. Defaults to `[0]` semantically.
   */
  readonly "success-exit-code"?: readonly number[] | undefined;
  /**
   * Runtime timeout in milliseconds.
   */
  readonly "timeout-ms"?: number | undefined;
};

/**
 * Scalar-or-array string list for composition typed refs.
 * 
 * Authoring accepts a string or an array of strings; canonical serialization
 * is always an array.
 */
export type CanonicalCompositionRefList = readonly string[];

/**
 * A named condition body keyed by `[condition.<id>]`.
 */
export type CanonicalCondition = {
  readonly "all"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "any"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "at-least"?: JsonValue | undefined;
  readonly "at-most"?: JsonValue | undefined;
  readonly "condition"?: string | undefined;
  readonly "count"?: string | undefined;
  readonly "description"?: string | undefined;
  readonly "elapsed-seconds-at-least"?: JsonValue | undefined;
  readonly "empty"?: string | undefined;
  readonly "equals"?: JsonValue | undefined;
  readonly "field"?: string | undefined;
  readonly "field-equals"?: JsonValue | undefined;
  readonly "greater-than"?: JsonValue | undefined;
  readonly "iteration"?: number | undefined;
  readonly "iteration-at-least"?: number | undefined;
  readonly "less-than"?: JsonValue | undefined;
  readonly "not"?: CanonicalGuardExpr | undefined;
  readonly "output"?: string | undefined;
  readonly "present"?: string | undefined;
  readonly "signal"?: string | undefined;
  readonly "slot"?: string | undefined;
};

/**
 * Duplicate-aware map of named conditions keyed by condition ID.
 */
export type CanonicalConditionMap = Readonly<Record<string, CanonicalCondition>>;

/**
 * A `[[relations.conflicts]]` entry: targetless — applies to the declaring
 * trait when `when` matches. Rejects `target`, `required`, `suggested`,
 * `conflicting`, `strength`, `max-depth`, `follows`, and `suppresses`.
 */
export type CanonicalConflicts = {
  readonly "reason": string;
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * The optional `[composition]` section.
 */
export type CanonicalContract = {
  /**
   * Traits or behavior axes that should not co-activate.
   * Accepted ref kinds: `trait`, `behavior`.
   */
  readonly "conflict"?: string | readonly string[] | undefined;
  /**
   * What to do when conflicts are found: `require-decision`,
   * `warn-and-isolate`, `fail-plan`.
   */
  readonly "conflict-policy"?: string | undefined;
  /**
   * How to combine with other traits: `structured`, `isolated`, `render-only`.
   */
  readonly "merge-strategy"?: string | undefined;
};

/**
 * Normalized list of contract ref strings for prompt input/output fields.
 * Accepts scalar-or-array at the decode boundary but always stores a
 * `Vec<String>` — source scalar-vs-array shape is not preserved as semantic
 * state. This type is distinct from [`TargetList`](crate::shared::TargetList)
 * so render target lists and protocol contract refs cannot drift together.
 */
export type CanonicalContractRefList = readonly string[];

/**
 * `ctx.traits` runtime/reporting extensions.
 */
export type CanonicalCtxExtensions = {
  readonly "subagent"?: CanonicalSubagentIntent | undefined;
};

/**
 * The optional `[activation]` section.
 */
export type CanonicalDeclaration = {
  /**
   * Manual activation is declarative data only; later phases gate runtime use.
   */
  readonly "manual"?: boolean | undefined;
  readonly "min-score"?: number | undefined;
  readonly "priority"?: number | undefined;
  /**
   * Ordered rules. Rules compose as OR during scoring.
   */
  readonly "rule"?: readonly CanonicalRule[] | undefined;
};

/**
 * A dependency declaration: alias, trait identity, version, and optional
 * source metadata.
 */
export type CanonicalDependency = {
  /**
   * Typed reference namespace for this dependency (e.g. `"aws"`).
   * 
   * Must be unique within the manifest. Used to qualify refs such as
   * `slot:aws/scope`. Must be a single-segment namespace without `:`, `.`,
   * `/`, or whitespace.
   */
  readonly "alias": string;
  /**
   * The trait ID being depended on (e.g. `"ctx/aws-log-primitives"`).
   */
  readonly "id": string;
  /**
   * Optional source metadata. When omitted, the source must be resolved
   * from the package-local `trait.lock` or provided explicitly by the caller.
   */
  readonly "source"?: JsonValue | undefined;
  /**
   * The trait version (e.g. `"0.1.0"`).
   */
  readonly "version": string;
};

/**
 * A typed digest value in `sha256:<hex>` format.
 */
export type CanonicalDigest = string;

/**
 * An `[[eval]]` declaration: a declared product evaluation check.
 * 
 * Eval declarations describe checks that can be run against a trait. They do
 * not execute by themselves. The `input` and `output` fields are product
 * refs (e.g. `render:agent-skills`, `fixture:fixtures/example.md`,
 * `trait:self`, `report:scenario-shape`), not repository test fixtures.
 */
export type CanonicalEval = {
  /**
   * Stable eval identifier (e.g. `"agent-skills-render"`).
   */
  readonly "id": string;
  /**
   * What the eval consumes (e.g. `render:agent-skills`, `trait:self`,
   * `fixture:fixtures/example.md`).
   */
  readonly "input"?: string | undefined;
  /**
   * Expected fixture, report, or comparison output (e.g.
   * `fixture:fixtures/example.md`, `report:scenario-shape`).
   */
  readonly "output"?: string | undefined;
  /**
   * Scenario IDs this eval covers (references to `[[scenario]]` IDs).
   * 
   * Canonical authoring uses singular `scenario` (scalar-or-array):
   * `scenario = "happy-path"` or
   * `scenario = ["happy-path", "edge-case"]`.
   */
  readonly "scenario"?: readonly string[] | undefined;
  /**
   * Eval/check type.
   */
  readonly "variant": CanonicalEvalVariant;
};

/**
 * The variant of an eval declaration.
 * 
 * MVP variants (`documentation`, `lint`, `golden-render`) have initial
 * implementation paths. Future variants (`behavioral`, `runtime`) are
 * declared but may be unsupported for execution.
 */
export type CanonicalEvalVariant = "documentation" | "lint" | "golden-render" | "behavioral" | "runtime";

/**
 * A loop's `on-exhausted` declaration: the keywords `"continue"`/`"block"`,
 * or one or more signal refs emitted when the loop continues past
 * exhaustion. A one-element sequence collapses to `One` on decode so each
 * meaning has exactly one canonical spelling.
 */
export type CanonicalExhaustionTarget = string | readonly string[];

/**
 * Top-level non-standard extensions namespace.
 */
export type CanonicalExtensions = {
  readonly "ctx"?: CanonicalCtxExtensions | undefined;
};

/**
 * Closed recovery-route declaration.
 */
export type CanonicalFailureRoute = {
  readonly "signal"?: string | undefined;
  readonly "step": string;
};

/**
 * A control failure either emits a legacy signal or abandons the current path
 * and schedules a later top-level recovery step.
 */
export type CanonicalFailureTarget = string | CanonicalFailureRoute;

/**
 * One guard expression. A string ref is either `signal:<id>` or
 * `condition:<id>`. An array is OR/any composition.
 */
export type CanonicalGuardExpr = string | readonly CanonicalGuardExpr[] | CanonicalGuardPredicate;

/**
 * Inline guard predicate form.
 */
export type CanonicalGuardPredicate = {
  readonly "all"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "any"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "at-least"?: JsonValue | undefined;
  readonly "at-most"?: JsonValue | undefined;
  readonly "condition"?: string | undefined;
  readonly "count"?: string | undefined;
  /**
   * Cumulative active-drive elapsed seconds (runtime-supplied evidence,
   * never a core wall clock) at least this threshold. Threshold is a JSON
   * number or a `{ ref = "slot:..."/"port:..." }` numeric reference.
   */
  readonly "elapsed-seconds-at-least"?: JsonValue | undefined;
  readonly "empty"?: string | undefined;
  readonly "equals"?: JsonValue | undefined;
  readonly "field"?: string | undefined;
  /**
   * Filters `count` to elements whose `field` equals this value. Paired
   * with `field`; meaningless alone. Kept distinct from `equals`, which is
   * already the count's threshold — one predicate needs both a "which
   * elements" and a "how many", and they cannot share a spelling.
   */
  readonly "field-equals"?: JsonValue | undefined;
  readonly "greater-than"?: JsonValue | undefined;
  readonly "iteration"?: number | undefined;
  readonly "iteration-at-least"?: number | undefined;
  readonly "less-than"?: JsonValue | undefined;
  readonly "not"?: CanonicalGuardExpr | undefined;
  readonly "output"?: string | undefined;
  /**
   * Presence-aware leaf (schema-version `"0.3"` only). Bare form is a local
   * optional input `port:*`; with `field`, a declared optional field of a
   * local `port:*`/`slot:*` object container. Yields `Matched`/`NotMatched`/`Unmeasurable`
   * tri-state internally; only `Matched` routes `true`.
   */
  readonly "present"?: string | undefined;
  readonly "signal"?: string | undefined;
  readonly "slot"?: string | undefined;
};

/**
 * A slug-identified guidance item with optional local render text.
 */
export type CanonicalGuidanceItem = {
  readonly "description"?: string | undefined;
  readonly "id": CanonicalSlug;
  readonly "summary"?: string | undefined;
};

/**
 * Scalar-or-array guidance list. Strings normalize to slug-only items.
 */
export type CanonicalGuidanceItemList = readonly CanonicalGuidanceItem[];

/**
 * Stable, durable trait identifier (not a display name).
 * 
 * Must be non-empty and use only lowercase letters, digits, and hyphens.
 * Display names and search labels are separate fields.
 */
export type CanonicalId = string;

/**
 * `[intent]` model.
 */
export type CanonicalIntent = {
  /**
   * Things to avoid doing.
   */
  readonly "avoid"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Things that must never happen.
   */
  readonly "block"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Areas to focus attention on.
   */
  readonly "focus"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Required outcomes or actions.
   */
  readonly "require"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
};

/**
 * Closed, policy-discriminated barrier join for a `parallel` sequence item.
 * Omission on `SequenceItem.join` is behaviorally identical to
 * `{ policy = "collect-in-order" }` — the P263 barrier.
 */
export type CanonicalJoinPolicy = {
  readonly "policy": "collect-in-order";
} | {
  readonly "destination": string;
  readonly "operation": CanonicalWriteOperation;
  readonly "policy": "reduce-merge";
  readonly "source": string;
} | {
  readonly "destination": string;
  readonly "guard": CanonicalGuardExpr;
  readonly "policy": "quorum-verdict";
  readonly "source": string;
};

/**
 * `[metadata]` facets: family, variant, job, domain, artifact, audience,
 * environment, tag.
 * 
 * All facets use kebab-case slug strings with scalar-or-array authoring.
 * Slug validation happens in the post-decode taxonomy pass. `family` and
 * `variant` are display-only: they never drive activation or canonical
 * trait resolution. Since P451, a declared `variant` additionally selects
 * which `[agent.variant.<v>.role.*]` config qualifier a run resolves
 * against (config routing, not activation or canonical resolution — see
 * `ctx_traits_io::harness_config::resolve_run_variant`).
 */
export type CanonicalMetadata = {
  readonly "artifact"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "audience"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "domain"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "environment"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Declared family identity for list grouping and consistency
   * advisories against the trait package ID. Display-only.
   */
  readonly "family"?: CanonicalSlug | undefined;
  readonly "job"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "tag"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Declared variant identity within `family`. Display-only.
   */
  readonly "variant"?: CanonicalSlug | undefined;
};

/**
 * Human-readable display name, not a durable identifier.
 */
export type CanonicalName = string;

/**
 * A named sequence block keyed by `[sequence.<id>]`.
 */
export type CanonicalNamedSequence = {
  /**
   * Human-readable description of the sequence block.
   */
  readonly "description"?: string | undefined;
  /**
   * Ordered items in this sequence block.
   */
  readonly "sequence"?: readonly CanonicalSequenceItem[] | undefined;
};

/**
 * Duplicate-aware map of named sequences keyed by sequence ID.
 */
export type CanonicalNamedSequenceMap = Readonly<Record<string, CanonicalNamedSequence>>;

/**
 * A step output sink.
 * 
 * Existing manifests serialize a plain typed ref string. New authoring may use
 * an inline table for slot write operations, e.g.
 * `{ slot = "slot:notes", operation = "append" }`.
 */
export type CanonicalOutputSink = string | {
  readonly "operation"?: CanonicalWriteOperation | undefined;
  readonly "slot": string;
};

/**
 * Normalized list of sequence output sinks.
 */
export type CanonicalOutputSinkList = readonly CanonicalOutputSink[];

/**
 * A `[[port]]` declaration: a boundary contract.
 */
export type CanonicalPort = {
  /**
   * Optional runtime default source for input ports. Static render/check do
   * not execute it; CLI/IO runtime may use it only with explicit permission.
   */
  readonly "default"?: CanonicalPortDefault | undefined;
  /**
   * Human-readable description.
   */
  readonly "description": string;
  /**
   * Whether this is an input or output port.
   */
  readonly "direction": CanonicalPortDirection;
  /**
   * Optional format preferences (e.g. `["markdown"]`).
   */
  readonly "format"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Port identifier (e.g. `"user-prompt"`, `"finding"`).
   */
  readonly "id": string;
  /**
   * Whether this port is optional. Defaults to `false`.
   */
  readonly "optional"?: boolean | undefined;
  /**
   * Schema ref (e.g. `"schema:text"`, `"schema:scope"`).
   */
  readonly "schema": string;
  /**
   * Optional display title.
   */
  readonly "title"?: string | undefined;
  /**
   * For output ports: the slot ref that exposes the value (`"slot:<id>"`).
   * Input ports must not declare `value`.
   */
  readonly "value"?: string | undefined;
};

/**
 * Runtime default source for an input port.
 */
export type CanonicalPortDefault = {
  readonly "command"?: CanonicalPortDefaultCommand | undefined;
  readonly "value"?: string | undefined;
};

/**
 * Command-backed runtime default source for an input port.
 */
export type CanonicalPortDefaultCommand = {
  readonly "argv"?: readonly string[] | undefined;
  readonly "capture"?: string | undefined;
  /**
   * Runtime stdout capture ceiling in bytes. Absent uses the IO host's
   * documented default-input capture ceiling. A capture that exceeds this
   * fails the run rather than landing a truncated value in the port.
   */
  readonly "capture-bytes"?: number | undefined;
  readonly "cmd"?: string | undefined;
  readonly "cwd"?: string | undefined;
  /**
   * Runtime timeout in milliseconds. Absent uses the IO host's documented
   * default-input timeout.
   */
  readonly "timeout-ms"?: number | undefined;
};

/**
 * Port direction: input or output.
 */
export type CanonicalPortDirection = "input" | "output";

/**
 * Scalar-or-array string list for activation predicates.
 * 
 * Authoring accepts either a string or an array of strings; canonical
 * serialization is always an array.
 */
export type CanonicalPredicateList = readonly string[];

/**
 * A `[procedure]` section: deterministic sequence orchestration.
 * 
 * Optional top-level section. When present, `description` must be non-empty
 * and `sequence` must be non-empty. The `input` and `output` contract fields
 * declare procedure-level boundary ports. `sequence` holds inline
 * `[[procedure.sequence]]` items; `sequence-order` optionally reorders them.
 */
export type CanonicalProcedure = {
  /**
   * Human-readable description of what the procedure accomplishes.
   */
  readonly "description": string;
  /**
   * Model-level input refs (e.g. `port:user-prompt`, `slot:scope`).
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Model-level output refs (e.g. `port:finding`, `slot:result`).
   */
  readonly "output"?: string | readonly string[] | undefined;
  /**
   * Ordered `[[procedure.sequence]]` items. Definition order is the default
   * execution order unless `sequence-order` is present.
   */
  readonly "sequence"?: readonly CanonicalSequenceItem[] | undefined;
  /**
   * Optional explicit ordering of sequence item IDs. If present, every
   * sequence item must have a unique ID, every listed ID must exist,
   * duplicate IDs are invalid, and unlisted items are invalid.
   */
  readonly "sequence-order"?: readonly string[] | undefined;
  /**
   * Require prepared worktree provenance before the procedure can expose
   * its first prompt or command frame.
   */
  readonly "worktree-required"?: boolean | undefined;
};

/**
 * Normalized list of ref strings for procedure `input`, `output`, and
 * `sequence` fields.
 * 
 * Accepts scalar-or-array at the decode boundary but always stores a
 * `Vec<String>`. Distinct from
 * [`ContractRefList`](crate::trait::prompt::ContractRefList) so procedure
 * contracts remain independent.
 */
export type CanonicalProcedureRefList = readonly string[];

/**
 * One ordered write in a closed `project` sequence item.
 * 
 * Runtime reads every slot source from one pre-step snapshot, optionally
 * selects one top-level object field, validates every destination write,
 * then commits all writes atomically. A literal source (P431) is a canonical
 * value declared on the projection itself rather than read from a slot;
 * literal-backed projections contribute no sequence input and reject
 * `field`. Destinations are local typed slots; `replace`, `append`, and
 * `increment` are the supported operations.
 */
export type CanonicalProjection = {
  readonly "destination": string;
  readonly "field"?: string | undefined;
  readonly "operation"?: CanonicalWriteOperation | undefined;
  readonly "source": CanonicalProjectionSource;
};

/**
 * One `procedure.sequence[].projection[].source`: either an existing local
 * slot ref, or a canonical typed literal wrapped as `{ literal = <value> }`.
 * The wrapper keeps the literal form unambiguous with the plain string
 * slot-ref shape — an unwrapped string literal would be indistinguishable
 * from `source = "slot:..."`.
 */
export type CanonicalProjectionSource = string | {
  readonly "literal": JsonValue;
};

/**
 * A `[prompt.<id>]` body: inline text or resource source plus contracts.
 * 
 * The prompt ID is the map key in `Trait.prompts`, not a field on this
 * struct.
 */
export type CanonicalPrompt = {
  /**
   * Human-readable description.
   */
  readonly "description"?: string | undefined;
  /**
   * Required input refs for this prompt (e.g. `port:user-prompt`,
   * `slot:scope`, `resource:checklist`). Accepts scalar-or-array,
   * normalized to a flat list.
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Output contract refs — local `slot:<id>` refs only. Accepts
   * scalar-or-array, normalized to a flat list.
   */
  readonly "output"?: string | readonly string[] | undefined;
  /**
   * Resource-backed prompt body source (`resource:<id>`).
   */
  readonly "source"?: string | undefined;
  /**
   * The prompt body text. May contain typed ref interpolations like
   * `{port:user-prompt}` or `{slot:scope}`.
   */
  readonly "text"?: string | undefined;
};

/**
 * A map of prompt IDs to prompt bodies that rejects duplicate keys at decode
 * time rather than silently overwriting.
 * 
 * This wraps [`BTreeMap<String, Prompt>`] with a custom `Deserialize` that
 * detects duplicate keys and returns an error before collapsing them.
 */
export type CanonicalPromptMap = Readonly<Record<string, CanonicalPrompt>>;

/**
 * A parsed canonical typed reference: `<kind>:<path>`.
 * 
 * The path is preserved verbatim from the source text. [`Self::ref_path`]
 * decomposes it into namespace and id for dependency-qualified refs.
 * `Display` round-trips to the canonical accepted text.
 */
export type CanonicalReference = string;

/**
 * The optional `[relations]` section.
 */
export type CanonicalRelations = {
  readonly "conflicts"?: readonly CanonicalConflicts[] | undefined;
  readonly "requires"?: readonly CanonicalRequires[] | undefined;
  readonly "suggests"?: readonly CanonicalSuggests[] | undefined;
};

/**
 * Scalar-or-array typed reference list for `when` conditions.
 */
export type CanonicalRelationsRefList = readonly CanonicalReference[];

/**
 * A `[[relations.requires]]` entry: the source needs the target.
 */
export type CanonicalRequires = {
  /**
   * Required explanation.
   */
  readonly "reason": string;
  /**
   * Required target: `port:*` or `trait:*`.
   */
  readonly "target": CanonicalReference;
  /**
   * Conditions that enable this relation: `rule:*` or `signal:*` refs.
   * Entries in one `when` list are AND; multiple entries model OR.
   */
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * An `[[resource]]` declaration: an external blob reference or inline text.
 * 
 * File-backed resources are materialized from IO evidence. Inline content is
 * materialized entirely within core without filesystem access.
 */
export type CanonicalResource = {
  /**
   * Inline resource body. Inline resources require no host IO.
   */
  readonly "content"?: string | undefined;
  /**
   * Canonical pin over the resource's expected file bytes, in
   * `sha256:<hex>` form. Presence marks this resource protected: IO must
   * verify actual bytes against this pin immediately before the resource
   * reaches a model or a command spawns, and `ctx traits check` reports
   * drift between this pin and the file on disk. Valid only on a
   * path-backed resource — inline and checklist bodies are already
   * canonical bytes with no filesystem path to verify. Omitted from
   * canonical serialization when absent, so every existing unpinned
   * declaration stays byte-identical. Adding or changing this pin changes
   * `Resource`'s canonical digest, which is how pinning or repinning a
   * resource moves the trait's machine-trust decision to stale.
   */
  readonly "digest"?: CanonicalDigest | undefined;
  /**
   * Advisory hint about the resource contents or usage.
   */
  readonly "hint"?: string | undefined;
  /**
   * Resource identifier (e.g. `"scope-schema"`).
   */
  readonly "id": string;
  /**
   * Typed inputs required by a resource template.
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Declared checklist items. Valid only alongside `variant = "checklist"`,
   * where they replace `path`/`content` as the resource body: the items are
   * canonical and the presented text is rendered from them, so no prose
   * copy of the checklist can drift from the typed one.
   */
  readonly "item"?: readonly CanonicalChecklistItem[] | undefined;
  /**
   * Path to the resource blob, relative to `root`.
   */
  readonly "path"?: string | undefined;
  /**
   * How this resource's body is presented to the model. Defaults to
   * `reference` for path-backed resources and `inline` for content or
   * checklist resources (see `effective_render()`); omitted from
   * canonical serialization when unset, so existing declarations stay
   * byte-identical.
   */
  readonly "render"?: CanonicalResourceRender | undefined;
  /**
   * Which root the declared `path` is relative to. Defaults to `package`
   * and is omitted from canonical serialization when default, so existing
   * package-relative declarations stay byte-identical.
   */
  readonly "root"?: CanonicalResourceRoot | undefined;
  /**
   * When to load the resource at runtime.
   */
  readonly "trigger"?: CanonicalResourceTrigger | undefined;
  /**
   * Optional resource kind. `template` resources may declare typed inputs.
   */
  readonly "variant"?: string | undefined;
};

/**
 * Normalized typed-ref inputs for resource templates.
 */
export type CanonicalResourceInputList = readonly string[];

export type CanonicalResourceRender = ResourceRender;

export type CanonicalResourceRoot = ResourceRoot;

export type CanonicalResourceTrigger = ResourceTrigger;

/**
 * One `[[activation.rule]]` declaration.
 */
export type CanonicalRule = {
  readonly "exclude-file-glob"?: CanonicalPredicateList | undefined;
  readonly "exclude-keyword"?: CanonicalPredicateList | undefined;
  readonly "explicit-phrase"?: CanonicalPredicateList | undefined;
  readonly "file-glob"?: CanonicalPredicateList | undefined;
  /**
   * Stable rule ID. Required and unique within `[activation]`.
   */
  readonly "id"?: string | undefined;
  readonly "language"?: CanonicalPredicateList | undefined;
  /**
   * Preferred initial load level: `discovery`, `summary`, or `full`.
   */
  readonly "load-level"?: string | undefined;
  readonly "mode"?: CanonicalPredicateList | undefined;
  /**
   * Human-readable reason shown by explanation surfaces.
   */
  readonly "reason"?: string | undefined;
  readonly "signal"?: CanonicalPredicateList | undefined;
  readonly "task-keyword"?: CanonicalPredicateList | undefined;
  readonly "weight"?: number | undefined;
};

/**
 * A `[[scenario]]` declaration: a product review behavior example.
 * 
 * Scenarios are behavior hints/specifications for humans, renderers, lint
 * checks, prompt review, and future behavioral eval harnesses. They are not
 * proof by themselves.
 */
export type CanonicalScenario = {
  /**
   * Stable scenario identifier (e.g. `"rust-review-positive"`).
   */
  readonly "id": string;
  /**
   * Example task or prompt input.
   */
  readonly "input"?: string | undefined;
  /**
   * Expected result, refusal, warning, or behavior description.
   */
  readonly "output"?: string | undefined;
  /**
   * Optional advisory tags for filtering or grouping.
   * 
   * Canonical authoring uses singular `tag` (scalar-or-array):
   * `tag = "security"` or `tag = ["security", "rust"]`.
   */
  readonly "tag"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Behavior variant: positive, negative, or edge.
   */
  readonly "variant": CanonicalScenarioVariant;
};

/**
 * The behavioral variant of a scenario.
 */
export type CanonicalScenarioVariant = "positive" | "negative" | "edge";

/**
 * A `[[schema]]` declaration: a named schema contract.
 * 
 * Must have exactly one of `resource`, `fields`, or scalar `schema`.
 */
export type CanonicalSchemaDeclaration = {
  /**
   * Closed set of allowed scalar values for scalar enum schemas.
   */
  readonly "allowed"?: readonly JsonValue[] | undefined;
  /**
   * Human-readable description of the schema.
   */
  readonly "description"?: string | undefined;
  /**
   * Inline field declarations for duck-typed compatibility.
   * Mutually exclusive with `resource`.
   */
  readonly "fields"?: Readonly<Record<string, CanonicalSchemaField>> | undefined;
  /**
   * Schema identifier (e.g. `"scope"`).
   */
  readonly "id": string;
  /**
   * Resource ref: `resource:<id>` pointing to an opaque blob.
   * Mutually exclusive with `fields`.
   */
  readonly "resource"?: string | undefined;
  /**
   * Scalar schema ref for closed-value enum schemas.
   * Mutually exclusive with `resource` and `fields`.
   */
  readonly "schema"?: string | undefined;
};

/**
 * One inline field declaration for duck-typed schema compatibility.
 */
export type CanonicalSchemaField = {
  /**
   * Optional closed set of allowed scalar values for this field.
   */
  readonly "allowed"?: readonly JsonValue[] | undefined;
  /**
   * Human-readable description.
   */
  readonly "description"?: string | undefined;
  /**
   * Advisory hint.
   */
  readonly "hint"?: string | undefined;
  /**
   * Whether this field is required.
   */
  readonly "required"?: boolean | undefined;
  /**
   * Field schema ref (e.g. `"schema:text"`, `"schema:number"`).
   */
  readonly "schema": string;
};

export type CanonicalSchemaForm = SchemaForm;

/**
 * Trait schema version string (e.g. "0.2").
 */
export type CanonicalSchemaVersion = string;

/**
 * Semantic version text (e.g. "0.1.0").
 */
export type CanonicalSemanticVersion = string;

/**
 * One `procedure.sequence[].input` entry.
 * 
 * An ordinary entry is a plain typed ref string (`port:*`, `slot:*`,
 * `resource:*`). A resource ref may additionally carry a `when` guard,
 * authored as `{ ref = "resource:<id>", when = <GuardExpr> }`; the runtime
 * includes that resource in the step's available context and
 * `resource_evidence` only when the guard matches at readiness. A slot ref
 * may instead be authored as `{ slot = "slot:<id>", optional = true }`
 * (P447): that slot never gates validation, planning, recovery, or runtime
 * readiness, and is omitted from the frame entirely until an accepted value
 * exists. Port inputs and plain (non-decorated) slot inputs remain
 * unconditional.
 */
export type CanonicalSequenceInput = string | {
  readonly "ref": string;
  readonly "when": CanonicalGuardExpr;
} | {
  readonly "optional": boolean;
  readonly "slot": string;
};

/**
 * Normalized list of `procedure.sequence[].input` entries.
 * 
 * Accepts scalar-or-array at the decode boundary, where each element is a
 * plain ref string, a guarded-resource table, or an optional-slot table
 * (P447). Always stores a `Vec<SequenceInput>`.
 */
export type CanonicalSequenceInputList = readonly CanonicalSequenceInput[];

/**
 * A `[[procedure.sequence]]` item: one item in the procedure, owned by the
 * procedure rather than by a separate top-level table.
 * 
 * `[[procedure.sequence]]` definition order is the default execution order.
 * An optional `id` allows `procedure.sequence-order` to customize ordering.
 */
export type CanonicalSequenceItem = {
  /**
   * Optional abstract agent role that should serve this executable item.
   */
  readonly "agent"?: string | undefined;
  /**
   * `parallel` ordered per-branch terminal failure policy. A branch with
   * no entry defaults to `panel-fail`.
   */
  readonly "branch-failure"?: readonly CanonicalBranchFailureEntry[] | undefined;
  /**
   * Ordered, author-order list of local `sequence:<id>` refs run as
   * independent branches of a `kind = "parallel"` item. Never sorted.
   */
  readonly "branches"?: string | readonly string[] | undefined;
  /**
   * See [`CommandPlan::capture_bytes`], for simple `cmd` shorthand.
   */
  readonly "capture-bytes"?: number | undefined;
  /**
   * Simple no-shell command shorthand for a command-backed sequence item.
   */
  readonly "cmd"?: string | undefined;
  /**
   * Explicit command declaration. `cmd` and `command` are mutually
   * exclusive source forms and lower to the same command plan.
   */
  readonly "command"?: CanonicalCommandDeclaration | undefined;
  /**
   * `for-each` concurrency request. Additive: `false`/absent is byte-identical
   * to documents authored before concurrency existed.
   */
  readonly "concurrent"?: boolean | undefined;
  /**
   * Declared signal refs this item may emit, either directly as refs or
   * derived from deterministic output predicates.
   */
  readonly "emits"?: readonly CanonicalSignalEmissionRule[] | undefined;
  /**
   * Optional format preferences. Accepted as a format-preference declaration on prompt/command items; rejected on control items.
   */
  readonly "format"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Optional stable identifier for sequence-order references.
   */
  readonly "id"?: string | undefined;
  /**
   * Runtime idle timeout in milliseconds, for simple `cmd` shorthand.
   */
  readonly "idle-timeout-ms"?: number | undefined;
  /**
   * Input refs (e.g. `port:user-prompt`, `slot:scope`, `resource:data`).
   * A resource entry may additionally be authored as a guarded table
   * (`{ ref = "resource:<id>", when = <GuardExpr> }`); the runtime
   * includes it in this step's frame only when the guard matches.
   */
  readonly "input"?: CanonicalSequenceInput | readonly CanonicalSequenceInput[] | undefined;
  /**
   * `for-each` per-item slot ref.
   */
  readonly "item"?: string | undefined;
  /**
   * `parallel` barrier join policy. Omitted is behaviorally identical to
   * `{ policy = "collect-in-order" }` (P263 barrier).
   */
  readonly "join"?: CanonicalJoinPolicy | undefined;
  /**
   * Explicit item kind. When omitted, `prompt`, `cmd`, and `command` fields
   * provide the current authoring sugar for prompt/command inference.
   */
  readonly "kind"?: CanonicalSequenceKind | undefined;
  /**
   * Required positive upper bound on `branches` length for a `parallel`
   * item. `branches.len()` must not exceed this bound.
   */
  readonly "max-branches"?: number | undefined;
  /**
   * Required `for-each` bound.
   */
  readonly "max-items"?: number | undefined;
  /**
   * Required loop bound.
   */
  readonly "max-iterations"?: number | undefined;
  /**
   * Local `schema:integer` input port resolved once at loop entry and frozen
   * into the runtime control frame. Mutually exclusive with
   * `max-iterations`.
   */
  readonly "max-iterations-from"?: string | undefined;
  /**
   * Runtime signal emitted when a for-each completes.
   */
  readonly "on-complete"?: string | undefined;
  /**
   * Loop exhaustion policy: `"continue"` (the default when omitted),
   * `"block"`, or one or more `signal:<id>` refs.
   * 
   * Continuing treats exhaustion as a normal outcome — the sequence
   * proceeds to the next item, and any declared signals are emitted as
   * recorded evidence a later guard may read (or ignore). Spending a
   * bounded budget without matching `until` means the work is unfinished,
   * which the following step is responsible for reading; it does not mean
   * the run is broken.
   * 
   * `"block"` stops the run at exhaustion, for procedures where an unmet
   * exit condition invalidates every step after the loop; no signal is
   * emitted in that case. A run started with strict loops blocks every
   * loop regardless of its declared policy, and suppresses signal
   * emission even when the declaration names one.
   */
  readonly "on-exhausted"?: CanonicalExhaustionTarget | undefined;
  /**
   * Legacy failure signal or structured forward recovery route.
   */
  readonly "on-failure"?: CanonicalFailureTarget | undefined;
  /**
   * Names the signal(s) to emit when `stop-if` is the arm that halts the
   * loop, so the trait's own terminal reason (e.g.
   * `recurring-blocker-unresolved`) is distinguishable from exhaustion in
   * the ledger, the receipt, and `run-status` — the runtime still reports
   * the accurate mechanism (`stop-if-matched`) alongside it. Requires
   * `stop-if`; the `"continue"`/`"block"` keywords are meaningless here
   * (a `stop-if` match always halts the loop) and are rejected.
   */
  readonly "on-stop"?: CanonicalExhaustionTarget | undefined;
  /**
   * Optional named sequence ref selected when a branch guard is false.
   */
  readonly "otherwise"?: string | undefined;
  /**
   * Output sinks (e.g. `port:finding`, `slot:result`, `schema:verdict`, or
   * `{ slot = "slot:notes", operation = "append" }`).
   */
  readonly "output"?: CanonicalOutputSink | readonly CanonicalOutputSink[] | undefined;
  /**
   * `for-each` list slot ref.
   */
  readonly "over"?: string | undefined;
  /**
   * Ordered deterministic writes for `kind = "project"`. All source values
   * are read before any destination is committed.
   */
  readonly "projection"?: readonly CanonicalProjection[] | undefined;
  /**
   * Prompt ref (`prompt:<id>`) or inline prompt text.
   */
  readonly "prompt"?: string | undefined;
  /**
   * Named sequence ref (`sequence:<id>`) for sequence/loop/for-each items.
   */
  readonly "sequence"?: string | undefined;
  /**
   * Loop terminal guard.
   */
  readonly "stop-if"?: CanonicalGuardExpr | undefined;
  /**
   * Exit codes treated as success for simple `cmd` shorthand.
   */
  readonly "success-exit-code"?: readonly number[] | undefined;
  /**
   * Runtime timeout in milliseconds for simple `cmd` shorthand.
   */
  readonly "timeout-ms"?: number | undefined;
  /**
   * Human-readable title for this sequence step.
   */
  readonly "title"?: string | undefined;
  /**
   * Loop success guard.
   */
  readonly "until"?: CanonicalGuardExpr | undefined;
  /**
   * Branch entry guard. A true guard selects `sequence`.
   */
  readonly "when"?: CanonicalGuardExpr | undefined;
};

/**
 * Sequence item kind. Omitted kind infers prompt or command from authored fields.
 */
export type CanonicalSequenceKind = "prompt" | "command" | "check" | "sequence" | "branch" | "loop" | "for-each" | "parallel" | "ask" | "project";

/**
 * A `[[session]]` declaration: a named, shareable session identity.
 */
export type CanonicalSession = {
  /**
   * Optional human-readable description of what this session is for.
   */
  readonly "description"?: string | undefined;
  /**
   * Session identifier, referenced by agents as `session:<id>`.
   */
  readonly "id": string;
};

/**
 * A `[[signal]]` declaration: a named event identity.
 */
export type CanonicalSignal = {
  /**
   * Human-readable description of when this signal fires.
   */
  readonly "description": string;
  /**
   * Signal identifier (e.g. `"needs-tests"`, `"missing-credentials"`).
   */
  readonly "id": string;
};

/**
 * A signal ref or a deterministic signal derivation rule.
 */
export type CanonicalSignalEmissionRule = string | {
  readonly "signal": string;
  readonly "when": CanonicalGuardExpr;
};

/**
 * A `[[slot]]` definition: a procedure run ledger value contract.
 */
export type CanonicalSlot = {
  /**
   * Human-readable description of what this slot represents.
   */
  readonly "description"?: string | undefined;
  /**
   * Advisory hint for the expected slot value, examples, or constraints
   * useful to a step prompt. Metadata only — schema remains the validation
   * contract.
   */
  readonly "hint"?: string | undefined;
  /**
   * Slot identifier (e.g. `"finding"`, `"scope"`, `"note-risk"`).
   */
  readonly "id": string;
  /**
   * Schema ref (e.g. `"schema:text"`, `"schema:scope"`,
   * `"[schema:scope]"`) or omitted.
   */
  readonly "schema"?: CanonicalSchemaForm | undefined;
};

/**
 * A kebab-case slug: lowercase letters/digits separated by single hyphens.
 * 
 * Deserializes permissively (raw string). Validation happens through
 * explicit construction (`Slug::new`, `Slug::new_at`) or the post-decode
 * taxonomy validation pass (`Slug::check`). Custom user slugs are allowed
 * when syntactically valid; no built-in vocabulary table is enforced.
 */
export type CanonicalSlug = string;

/**
 * Kebab-case slug list: accepts scalar-or-array input and normalizes to
 * `Vec<Slug>`.
 * 
 * Always serializes as an array (canonical output). Slug shape validation
 * happens in the post-decode taxonomy pass, not during deserialization, so
 * diagnostics carry canonical field paths.
 */
export type CanonicalSlugList = readonly CanonicalSlug[];

/**
 * Advisory subagent intent metadata.
 */
export type CanonicalSubagentIntent = {
  readonly "allowed-surface"?: readonly string[] | undefined;
  readonly "allowed-tool"?: readonly string[] | undefined;
  readonly "evidence-expectation"?: readonly string[] | undefined;
  readonly "forbidden-model-hint"?: readonly string[] | undefined;
  readonly "forbidden-service-tier-hint"?: readonly string[] | undefined;
  readonly "handoff-expectation"?: readonly string[] | undefined;
  readonly "load-level"?: string | undefined;
  readonly "required-inherited-trait"?: readonly string[] | undefined;
  readonly "role"?: string | undefined;
  readonly "task-boundary"?: string | undefined;
};

/**
 * A `[[relations.suggests]]` entry: advisory influence toward target.
 */
export type CanonicalSuggests = {
  readonly "reason": string;
  /**
   * Suggested target: `trait:*` or `port:*`.
   */
  readonly "target": CanonicalReference;
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * Short human-readable description.
 */
export type CanonicalSummary = string;

export type CanonicalWriteOperation = WriteOperation;

/**
 * The canonical trait root aggregate: identity, guidance, activation, ports,
 * slots, schemas, signals, prompts, procedure, composition, and relations.
 */
export type CanonicalTrait = {
  /**
   * Declaration matching declarations. Pure data only; runtime activation is
   * resolved by later gated phases.
   */
  readonly "activation"?: CanonicalDeclaration | undefined;
  /**
   * Declared abstract agent roles for multi-harness procedure routing.
   */
  readonly "agent"?: readonly CanonicalAgent[] | undefined;
  /**
   * Behavior: how the trait should act.
   */
  readonly "behavior"?: CanonicalBehavior | undefined;
  /**
   * Contract contract: conflict declarations and merge policy.
   * Pure data only; runtime composition planning is separate.
   */
  readonly "composition"?: CanonicalContract | undefined;
  /**
   * Named typed conditions (`[condition.<id>]`).
   */
  readonly "condition"?: CanonicalConditionMap | undefined;
  /**
   * Dependencies that this trait references by alias, e.g.
   * `resource:aws/rubric`. Resolution is performed at the IO/check boundary.
   */
  readonly "dependency"?: readonly CanonicalDependency[] | undefined;
  /**
   * Product eval declarations: declared checks that can be run.
   */
  readonly "eval"?: readonly CanonicalEval[] | undefined;
  /**
   * Non-standard ctx-specific advisory/reporting extensions.
   */
  readonly "extensions"?: CanonicalExtensions | undefined;
  readonly "id": CanonicalId;
  /**
   * Intent: what the trait requires, focuses on, avoids, and blocks.
   */
  readonly "intent"?: CanonicalIntent | undefined;
  /**
   * Searchable metadata facets. Separate from activation.
   */
  readonly "metadata"?: CanonicalMetadata | undefined;
  readonly "name": CanonicalName;
  /**
   * Port declarations: boundary contracts for trait dataflow.
   */
  readonly "port"?: readonly CanonicalPort[] | undefined;
  /**
   * Optional procedure: deterministic sequence orchestration.
   */
  readonly "procedure"?: CanonicalProcedure | undefined;
  /**
   * Prompt definitions: reusable prompt bodies with optional contracts.
   * Map key is the prompt ID (TOML `[prompt.<id>]`).
   */
  readonly "prompt"?: CanonicalPromptMap | undefined;
  /**
   * Canonical relations: trait-to-trait requires, suggests, and targetless
   * conflicts. Pure data only; graph construction and evaluation are
   * separate deterministic passes.
   */
  readonly "relations"?: CanonicalRelations | undefined;
  /**
   * Resource declarations: opaque blob references for schema bodies and
   * external data.
   */
  readonly "resource"?: readonly CanonicalResource[] | undefined;
  /**
   * Product review scenarios: positive, negative, and edge behavior
   * examples. Not executable test cases.
   */
  readonly "scenario"?: readonly CanonicalScenario[] | undefined;
  /**
   * Local schema declarations: named object schema contracts backed by
   * resource refs or inline fields.
   */
  readonly "schema"?: readonly CanonicalSchemaDeclaration[] | undefined;
  readonly "schema-version": CanonicalSchemaVersion;
  /**
   * Named reusable sequence blocks (`[sequence.<id>]`).
   */
  readonly "sequence"?: CanonicalNamedSequenceMap | undefined;
  /**
   * Declared session identities: named, shareable session bindings that
   * `[[agent]].session` references target.
   */
  readonly "session"?: readonly CanonicalSession[] | undefined;
  /**
   * Declared signal identities for procedure sequence emission.
   */
  readonly "signal"?: readonly CanonicalSignal[] | undefined;
  /**
   * Slot definitions: procedure run ledger value contracts.
   */
  readonly "slot"?: readonly CanonicalSlot[] | undefined;
  readonly "summary": CanonicalSummary;
  /**
   * Native family variant identity. This is deliberately absent from 0.2
   * documents, preserving their encoded bytes and digest semantics.
   */
  readonly "variant"?: string | undefined;
  readonly "version": CanonicalSemanticVersion;
};

/**
 * The CDK's pre-synth draft document: `Trait`'s identity fields
 * (`id`, `schema-version`, `version`, `name`, `summary`) are optional.
 */
export type CanonicalTraitDraft = {
  /**
   * Declaration matching declarations. Pure data only; runtime activation is
   * resolved by later gated phases.
   */
  readonly "activation"?: CanonicalDeclaration | undefined;
  /**
   * Declared abstract agent roles for multi-harness procedure routing.
   */
  readonly "agent"?: readonly CanonicalAgent[] | undefined;
  /**
   * Behavior: how the trait should act.
   */
  readonly "behavior"?: CanonicalBehavior | undefined;
  /**
   * Contract contract: conflict declarations and merge policy.
   * Pure data only; runtime composition planning is separate.
   */
  readonly "composition"?: CanonicalContract | undefined;
  /**
   * Named typed conditions (`[condition.<id>]`).
   */
  readonly "condition"?: CanonicalConditionMap | undefined;
  /**
   * Dependencies that this trait references by alias, e.g.
   * `resource:aws/rubric`. Resolution is performed at the IO/check boundary.
   */
  readonly "dependency"?: readonly CanonicalDependency[] | undefined;
  /**
   * Product eval declarations: declared checks that can be run.
   */
  readonly "eval"?: readonly CanonicalEval[] | undefined;
  /**
   * Non-standard ctx-specific advisory/reporting extensions.
   */
  readonly "extensions"?: CanonicalExtensions | undefined;
  readonly "id"?: CanonicalId | undefined;
  /**
   * Intent: what the trait requires, focuses on, avoids, and blocks.
   */
  readonly "intent"?: CanonicalIntent | undefined;
  /**
   * Searchable metadata facets. Separate from activation.
   */
  readonly "metadata"?: CanonicalMetadata | undefined;
  readonly "name"?: CanonicalName | undefined;
  /**
   * Port declarations: boundary contracts for trait dataflow.
   */
  readonly "port"?: readonly CanonicalPort[] | undefined;
  /**
   * Optional procedure: deterministic sequence orchestration.
   */
  readonly "procedure"?: CanonicalProcedure | undefined;
  /**
   * Prompt definitions: reusable prompt bodies with optional contracts.
   * Map key is the prompt ID (TOML `[prompt.<id>]`).
   */
  readonly "prompt"?: CanonicalPromptMap | undefined;
  /**
   * Canonical relations: trait-to-trait requires, suggests, and targetless
   * conflicts. Pure data only; graph construction and evaluation are
   * separate deterministic passes.
   */
  readonly "relations"?: CanonicalRelations | undefined;
  /**
   * Resource declarations: opaque blob references for schema bodies and
   * external data.
   */
  readonly "resource"?: readonly CanonicalResource[] | undefined;
  /**
   * Product review scenarios: positive, negative, and edge behavior
   * examples. Not executable test cases.
   */
  readonly "scenario"?: readonly CanonicalScenario[] | undefined;
  /**
   * Local schema declarations: named object schema contracts backed by
   * resource refs or inline fields.
   */
  readonly "schema"?: readonly CanonicalSchemaDeclaration[] | undefined;
  readonly "schema-version"?: CanonicalSchemaVersion | undefined;
  /**
   * Named reusable sequence blocks (`[sequence.<id>]`).
   */
  readonly "sequence"?: CanonicalNamedSequenceMap | undefined;
  /**
   * Declared session identities: named, shareable session bindings that
   * `[[agent]].session` references target.
   */
  readonly "session"?: readonly CanonicalSession[] | undefined;
  /**
   * Declared signal identities for procedure sequence emission.
   */
  readonly "signal"?: readonly CanonicalSignal[] | undefined;
  /**
   * Slot definitions: procedure run ledger value contracts.
   */
  readonly "slot"?: readonly CanonicalSlot[] | undefined;
  readonly "summary"?: CanonicalSummary | undefined;
  /**
   * Native family variant identity. This is deliberately absent from 0.2
   * documents, preserving their encoded bytes and digest semantics.
   */
  readonly "variant"?: string | undefined;
  readonly "version"?: CanonicalSemanticVersion | undefined;
};

