// Generated by `ctx traits internal sdk-generate` from Rust SDK vocabulary.
// Do not edit by hand.

export type JsonValue = null | boolean | number | string | readonly JsonValue[] | JsonObject;
export type JsonObject = { readonly [key: string]: JsonValue | undefined };

export type RefKind = "agent" | "condition" | "port" | "prompt" | "resource" | "rule" | "schema" | "sequence" | "session" | "setting" | "signal" | "slot" | "trait";
export type SchemaBuiltin = "schema:text" | "schema:boolean" | "schema:number" | "schema:integer" | "schema:any" | "schema:checklist-item";
export type SchemaForm = SchemaBuiltin | `[${string}]` | `(${string})`;
export const schemaForms = {
  list: { prefix: "[", separator: "", suffix: "]" },
  union: { prefix: "(", separator: "|", suffix: ")" },
} as const;
export type WriteOperation = "replace" | "append" | "merge" | { readonly "set-field": string } | "increment";
export type SynthFormat = "toml" | "json" | "yaml";
export type RuntimeSurface = "wasm-core" | "wasm-plugin" | "cli-json";
export type RuntimeOperation = "validate" | "normalize" | "synth" | "audit" | "import-plan" | "render" | "compose" | "resolve" | "explain" | "pack" | "cache-plan" | "ledger-update";

/** Built-in ToneBuiltIn values.
 * @property plain Everyday language over domain jargon.
 * @property technical Precise implementation and API terminology.
 * @property direct Conclusions and blockers stated plainly, never softened.
 * @property warm Human, constructive phrasing that still names the risk.
 * @property formal Precise phrasing, complete sentences, stable terminology.
 * @property calm Risk described without alarm, blame, or overstated certainty.
 * @property critical Claims inspected before they are accepted.
 * @property encouraging Useful direction acknowledged without softening findings.
 * @property curious Targeted questions about what is unknown.
 */
export type ToneBuiltIn = "plain" | "technical" | "direct" | "warm" | "formal" | "calm" | "critical" | "encouraging" | "curious";
export const Tone = {
  /** Everyday language over domain jargon. Explained as one person talking to another, without sloganeering, rhetorical flourish, or a term of art where a common word carries the same meaning. */
  plain: "plain",
  /** Precise implementation and API terminology. Concrete types, contracts, boundaries, and runtime effects named directly, in place of vaguer description that would need re-deriving. */
  technical: "technical",
  /** Conclusions and blockers stated plainly, never softened. The finding said first and said clearly, with respect but without hedging that leaves the reader unsure whether something is wrong. */
  direct: "direct",
  /** Human, constructive phrasing that still names the risk. Feedback that reads as one person helping another, without letting the warmth hide what has to be fixed. */
  warm: "warm",
  /** Precise phrasing, complete sentences, stable terminology. A register that stays consistent across a document, preferring the same word for the same thing over casual variation. */
  formal: "formal",
  /** Risk described without alarm, blame, or overstated certainty. Severity carried by what is said rather than how loudly, so a real emergency still reads as one. */
  calm: "calm",
  /** Claims inspected before they are accepted. Correctness, safety, trust, and evidence gaps looked for first, rather than the happy path taken at its word. */
  critical: "critical",
  /** Useful direction acknowledged without softening findings. Progress named where it is real, while the concrete problems keep their weight. */
  encouraging: "encouraging",
  /** Targeted questions about what is unknown. Gaps in evidence turned into specific questions rather than filled with a plausible guess. */
  curious: "curious",
} as const satisfies Record<string, ToneBuiltIn>;

/** Built-in MethodBuiltIn values.
 * @property restate-to-confirm The request played back in one's own words before acting.
 * @property steelman The strongest case against the conclusion, stated fairly.
 * @property implications-first What each fact constrains, breaks, or enables.
 * @property push-back Disagreement with a premise the evidence does not support.
 * @property evidence-first Findings grounded in observed evidence.
 * @property socratic Questions that expose assumptions and tradeoffs.
 * @property options-first Viable options and their tradeoffs before a recommendation.
 * @property critique-first Material issues before praise or summary.
 * @property first-principles The underlying constraint explained before the local convention.
 * @property divergent Several distinct directions generated before narrowing.
 * @property convergent Options reduced to the smallest defensible next step.
 */
export type MethodBuiltIn = "restate-to-confirm" | "steelman" | "implications-first" | "push-back" | "evidence-first" | "socratic" | "options-first" | "critique-first" | "first-principles" | "divergent" | "convergent";
export const Method = {
  /** The request played back in one's own words before acting. The understanding of what was asked stated plainly first, so a misreading surfaces before the work built on it does. */
  restateToConfirm: "restate-to-confirm",
  /** The strongest case against the conclusion, stated fairly. The best version of the opposing argument put honestly, along with what makes it fail — not a weak form set up to be knocked down. */
  steelman: "steelman",
  /** What each fact constrains, breaks, or enables. The consequence carried alongside the observation, so a reader learns what follows rather than only what is. */
  implicationsFirst: "implications-first",
  /** Disagreement with a premise the evidence does not support. A stated approach or assumption challenged directly, carrying the evidence for the challenge, rather than followed because it was asked for. */
  pushBack: "push-back",
  /** Findings grounded in observed evidence. Each claim tied to the source, command, artifact, or report behind it, with uncertainty stated where the evidence runs out. */
  evidenceFirst: "evidence-first",
  /** Questions that expose assumptions and tradeoffs. Reasoning drawn out through focused questions rather than delivered as a lecture through every answer. */
  socratic: "socratic",
  /** Viable options and their tradeoffs before a recommendation. The alternatives named clearly enough to choose between, rather than a single path presented as the only one. */
  optionsFirst: "options-first",
  /** Material issues before praise or summary. What is wrong surfaced at the top, where it cannot be missed behind an account of what is fine. */
  critiqueFirst: "critique-first",
  /** The underlying constraint explained before the local convention. Why a rule exists established first, so a reader can tell when it applies and when it does not. */
  firstPrinciples: "first-principles",
  /** Several distinct directions generated before narrowing. Genuinely different approaches explored, rather than one idea and its variations. */
  divergent: "divergent",
  /** Options reduced to the smallest defensible next step. A decision reached and stated, once the evidence supports narrowing. */
  convergent: "convergent",
} as const satisfies Record<string, MethodBuiltIn>;

/** Built-in VerbosityBuiltIn values.
 * @property brief Compact output, expanded only where risk needs explaining.
 * @property terse The shortest useful answer.
 * @property normal Enough context to act without exhaustive background.
 * @property detailed Rationale, evidence, and edge cases included.
 */
export type VerbosityBuiltIn = "brief" | "terse" | "normal" | "detailed";
export const Verbosity = {
  /** Compact output, expanded only where risk needs explaining. The short form by default, with length spent on impact or a repair rather than on general commentary. */
  brief: "brief",
  /** The shortest useful answer. Only the facts or actions the task needs, with nonessential commentary omitted entirely. */
  terse: "terse",
  /** Enough context to act without exhaustive background. The answer plus what makes it usable, stopping short of a full account of how it was reached. */
  normal: "normal",
  /** Rationale, evidence, and edge cases included. The longer form, used where trust or correct application depends on the reader seeing the reasoning. */
  detailed: "detailed",
} as const satisfies Record<string, VerbosityBuiltIn>;

/** Built-in FormatBuiltIn values.
 * @property bullets Related facts grouped as concise bullets.
 * @property table Parallel content laid out for comparison.
 * @property checklist Verification items, each independently confirmable.
 * @property findings-first Material findings ahead of general commentary.
 * @property answer-first The conclusion before the explanation.
 * @property questions-first Blocking questions before anything else.
 * @property steps Ordered actions in the sequence they are performed.
 */
export type FormatBuiltIn = "bullets" | "table" | "checklist" | "findings-first" | "answer-first" | "questions-first" | "steps";
export const Format = {
  /** Related facts grouped as concise bullets. Scannable structure without nesting hierarchy the content does not need. */
  bullets: "bullets",
  /** Parallel content laid out for comparison. The form for options, statuses, fields, or tradeoffs, where the point is what differs across rows. */
  table: "table",
  /** Verification items, each independently confirmable. Concrete and observable steps, so a reader can establish each one without interpreting it. */
  checklist: "checklist",
  /** Material findings ahead of general commentary. Ordered by severity, with residual risk and validation gaps kept separate from the findings themselves. */
  findingsFirst: "findings-first",
  /** The conclusion before the explanation. The requested value or verdict stated first, with caveats and support following it. */
  answerFirst: "answer-first",
  /** Blocking questions before anything else. Only the questions that change the answer, asked before work proceeds on a guess. */
  questionsFirst: "questions-first",
  /** Ordered actions in the sequence they are performed. Each step actionable on its own, in the order that actually works. */
  steps: "steps",
} as const satisfies Record<string, FormatBuiltIn>;

/** Built-in DirectnessBuiltIn values.
 * @property low Softened phrasing that still preserves correctness and caveats.
 * @property medium Issues stated plainly in a collaborative register.
 * @property high Material blockers stated without hedging.
 */
export type DirectnessBuiltIn = "low" | "medium" | "high";
export const Directness = {
  /** Softened phrasing that still preserves correctness and caveats. Tact given room where context benefits from it, without losing what the reader needs to know. */
  low: "low",
  /** Issues stated plainly in a collaborative register. Problems named without softening, in language that reads as working together on them. */
  medium: "medium",
  /** Material blockers stated without hedging. Clear blocker language for correctness, safety, and trust risk, where ambiguity would cost more than bluntness. */
  high: "high",
} as const satisfies Record<string, DirectnessBuiltIn>;

/** Built-in ScopeControlBuiltIn values.
 * @property strict Nothing outside the requested scope.
 * @property moderate Limited adjacent scope where it reduces risk.
 * @property expansive Broader context surfaced where it matters.
 */
export type ScopeControlBuiltIn = "strict" | "moderate" | "expansive";
export const ScopeControl = {
  /** Nothing outside the requested scope. Broad rewrites, unrelated style preference, and speculative architecture all left alone. */
  strict: "strict",
  /** Limited adjacent scope where it reduces risk. Nearby issues raised when they bear on the requested change, and otherwise left. */
  moderate: "moderate",
  /** Broader context surfaced where it matters. Adjacent risk, alternatives, and follow-up work named when they materially affect the outcome. */
  expansive: "expansive",
} as const satisfies Record<string, ScopeControlBuiltIn>;

/** Built-in InitiativeBuiltIn values.
 * @property wait-for-instruction No action until explicitly instructed.
 * @property ask-before-expanding-scope Confirmation sought before taking on adjacent work.
 * @property suggest-next-steps Focused follow-ups offered, not performed.
 * @property proactively-execute-safe-steps Low-risk requested work carried through.
 */
export type InitiativeBuiltIn = "wait-for-instruction" | "ask-before-expanding-scope" | "suggest-next-steps" | "proactively-execute-safe-steps";
export const Initiative = {
  /** No action until explicitly instructed. Implementation and further investigation both held until asked for. */
  waitForInstruction: "wait-for-instruction",
  /** Confirmation sought before taking on adjacent work. A pause at the boundary of the request, rather than a decision made on the requester's behalf. */
  askBeforeExpandingScope: "ask-before-expanding-scope",
  /** Focused follow-ups offered, not performed. Concise next actions named, left for the requester to choose. */
  suggestNextSteps: "suggest-next-steps",
  /** Low-risk requested work carried through. Implementation and verification completed where the risk is contained and the request is clear. */
  proactivelyExecuteSafeSteps: "proactively-execute-safe-steps",
} as const satisfies Record<string, InitiativeBuiltIn>;

/** Built-in UncertaintyBuiltIn values.
 * @property ask-when-blocked A stop and a question when information is missing.
 * @property state-assumptions Assumptions called out where they affect the outcome.
 * @property list-unknowns Known evidence separated from what is still unresolved.
 * @property refuse-to-guess No invented facts where evidence is required.
 */
export type UncertaintyBuiltIn = "ask-when-blocked" | "state-assumptions" | "list-unknowns" | "refuse-to-guess";
export const Uncertainty = {
  /** A stop and a question when information is missing. The specific missing decision or access named, rather than progress made on an assumption. */
  askWhenBlocked: "ask-when-blocked",
  /** Assumptions called out where they affect the outcome. What was taken as given, said beside the answer, implementation, or validation that rests on it. */
  stateAssumptions: "state-assumptions",
  /** Known evidence separated from what is still unresolved. The open questions that could change the conclusion, listed as open rather than folded into the conclusion. */
  listUnknowns: "list-unknowns",
  /** No invented facts where evidence is required. The missing evidence named, and the answer withheld, rather than a plausible value supplied in its place. */
  refuseToGuess: "refuse-to-guess",
} as const satisfies Record<string, UncertaintyBuiltIn>;

/** Built-in IntentBuiltIn values.
 * @property accretion A parallel solution added beside an existing one instead of consolidating.
 * @property annotation-fidelity Each annotation surviving as exactly one checklist item.
 * @property behavior-preserving-default Observable behavior staying as it is unless the task changes it.
 * @property big-rewrite Rewriting a subsystem where a narrow fix would do.
 * @property bounded-refinement A review-and-repair loop with a condition that ends it.
 * @property correctness Whether the code does the right thing, ahead of how it reads.
 * @property data-loss Behavior that can delete, corrupt, overwrite, leak, or strand data.
 * @property destructive-change Deleting data or rewriting history.
 * @property duplication Logic copied where it should be shared and evolve together.
 * @property elegance Clear, cohesive design over clever or incidental complexity.
 * @property gates-green-before-commit The repository's validation gates passing before a commit.
 * @property gold-plating Polish or features nobody asked for.
 * @property inspect-changed-behavior Reading the diff, nearby code, and tests before drawing conclusions.
 * @property interface-widening Public surface growing without a concrete caller.
 * @property leanness Only what the requested outcome needs.
 * @property maintainability Complexity, coupling, and brittleness that make future change harder.
 * @property match-surrounding-style Code that reads like its neighbours.
 * @property over-engineering Generality built ahead of demonstrated need.
 * @property performance Avoidable expensive work.
 * @property policy-bypass Working around user, repository, host, or organization policy.
 * @property pragmatism The smallest practical change that satisfies the contract.
 * @property preserve-scope Staying inside the requested task.
 * @property report-actionable-finding A finding carrying what is wrong, why it matters, and where.
 * @property reuse-over-reimplement Extracting shared logic instead of copying it.
 * @property review-before-final Inspecting completed work against its requirements before calling it done.
 * @property robustness Correctness under ordinary failure and boundary conditions.
 * @property role-attributed-output Output labelled with the role that produced or reviewed it.
 * @property rubber-stamp-review Approval without substantive review.
 * @property scope-creep Expanding past what was asked.
 * @property secret-exfiltration Revealing, copying, uploading, or moving secrets.
 * @property security Permission handling, injection risk, and unsafe data exposure.
 * @property silent-deviation Adapting around a contradicted plan without recording it.
 * @property specific Observations naming the affected behavior, artifact, or location.
 * @property speculative-claim A guess presented as fact.
 * @property state-assumptions Assumptions made visible beside the claims they support.
 * @property style-only Cosmetic feedback where no style review was asked for.
 * @property taste-only-blocking Subjective preference treated as a blocking defect.
 * @property tests Coverage, assertions, uncovered branches, and stale tests.
 * @property unapproved-network Network access without explicit allowance.
 * @property unbounded-loop Refinement with no stop condition.
 * @property unrequested-refactor Changing code outside the requested change.
 * @property unsafe-command Commands that can destroy data or alter system state.
 * @property user-impact The user-visible consequence of a finding.
 * @property verbatim-execution An agreed draft executed exactly, with departures recorded.
 * @property verifiable-goal The task restated as a condition that can be checked.
 * @property verify-coverage Whether changed behavior is covered by anything.
 * @property weaken-tests-to-pass Loosening a test instead of repairing the implementation.
 */
export type IntentBuiltIn = "accretion" | "annotation-fidelity" | "behavior-preserving-default" | "big-rewrite" | "bounded-refinement" | "correctness" | "data-loss" | "destructive-change" | "duplication" | "elegance" | "gates-green-before-commit" | "gold-plating" | "inspect-changed-behavior" | "interface-widening" | "leanness" | "maintainability" | "match-surrounding-style" | "over-engineering" | "performance" | "policy-bypass" | "pragmatism" | "preserve-scope" | "report-actionable-finding" | "reuse-over-reimplement" | "review-before-final" | "robustness" | "role-attributed-output" | "rubber-stamp-review" | "scope-creep" | "secret-exfiltration" | "security" | "silent-deviation" | "specific" | "speculative-claim" | "state-assumptions" | "style-only" | "taste-only-blocking" | "tests" | "unapproved-network" | "unbounded-loop" | "unrequested-refactor" | "unsafe-command" | "user-impact" | "verbatim-execution" | "verifiable-goal" | "verify-coverage" | "weaken-tests-to-pass";
export const Intent = {
  /** A parallel solution added beside an existing one instead of consolidating. Related behavior that grows a second helper, branch, or path next to the one already handling it, rather than being unified with it. */
  accretion: "accretion",
  /** Each annotation surviving as exactly one checklist item. Every human annotation maps to one actionable item — none dropped, none merged into another, none silently reworded into something else. */
  annotationFidelity: "annotation-fidelity",
  /** Observable behavior staying as it is unless the task changes it. The existing contract holds by default: a change that alters what callers observe is a deliberate act, not a side effect of the work. */
  behaviorPreservingDefault: "behavior-preserving-default",
  /** Rewriting a subsystem where a narrow fix would do. Replacing working structure wholesale when the requested outcome needed a contained change. */
  bigRewrite: "big-rewrite",
  /** A review-and-repair loop with a condition that ends it. Repair cycles that recheck what was fixed and stop at a stated acceptance condition rather than running until something else intervenes. */
  boundedRefinement: "bounded-refinement",
  /** Whether the code does the right thing, ahead of how it reads. Real behavior gaps and defects, weighed above naming, formatting, and style preference. */
  correctness: "correctness",
  /** Behavior that can delete, corrupt, overwrite, leak, or strand data. Operations whose failure mode costs data rather than time — a migration dropping a column before the copy, a write that cannot be undone. */
  dataLoss: "data-loss",
  /** Deleting data or rewriting history. Actions that remove or rewrite what already exists, where recovery is difficult or impossible without a backup. */
  destructiveChange: "destructive-change",
  /** Logic copied where it should be shared and evolve together. Two or more sites carrying the same behavior, so a future change has to find and update every copy to stay correct. */
  duplication: "duplication",
  /** Clear, cohesive design over clever or incidental complexity. Structure that reads as one idea, rather than an assembly whose parts only make sense in the order they were added. */
  elegance: "elegance",
  /** The repository's validation gates passing before a commit. The checks the project itself defines — build, tests, lint — run and resolved rather than deferred past the commit that broke them. */
  gatesGreenBeforeCommit: "gates-green-before-commit",
  /** Polish or features nobody asked for. Optional enhancement delivered alongside the requested outcome, expanding what has to be reviewed and maintained. */
  goldPlating: "gold-plating",
  /** Reading the diff, nearby code, and tests before drawing conclusions. Findings grounded in what the change actually does, established by looking at it rather than inferring from its description. */
  inspectChangedBehavior: "inspect-changed-behavior",
  /** Public surface growing without a concrete caller. An export, parameter, or option added for a use that has not appeared yet, which then has to be supported once it exists. */
  interfaceWidening: "interface-widening",
  /** Only what the requested outcome needs. The change sized to its purpose, with anything beyond that recognized as a separate decision rather than a free addition. */
  leanness: "leanness",
  /** Complexity, coupling, and brittleness that make future change harder. Structure whose cost lands on the next person: unclear naming, tangled dependencies, branching that must be held in the head all at once. */
  maintainability: "maintainability",
  /** Code that reads like its neighbours. Existing convention in the file honored over personal preference, so a change does not announce itself by looking different from the code around it. */
  matchSurroundingStyle: "match-surrounding-style",
  /** Generality built ahead of demonstrated need. Abstraction, configurability, or defensive handling for cases that have not been shown to occur. */
  overEngineering: "over-engineering",
  /** Avoidable expensive work. Cost that the task did not require — an accidental quadratic over a large collection, repeated work that could be done once. */
  performance: "performance",
  /** Working around user, repository, host, or organization policy. Routing past a permission prompt, a repository rule, or an organizational constraint rather than satisfying it or surfacing it. */
  policyBypass: "policy-bypass",
  /** The smallest practical change that satisfies the contract. What the stated requirement actually needs, chosen over the more thorough or more general thing nearby. */
  pragmatism: "pragmatism",
  /** Staying inside the requested task. Adjacent work named as an option rather than performed, so the boundary of the change stays where it was agreed. */
  preserveScope: "preserve-scope",
  /** A finding carrying what is wrong, why it matters, and where. Enough for someone else to act: the defect, its consequence, and the location, rather than an observation that has to be re-derived. */
  reportActionableFinding: "report-actionable-finding",
  /** Extracting shared logic instead of copying it. Existing behavior found and reused, so one definition serves both callers rather than two definitions drifting apart. */
  reuseOverReimplement: "reuse-over-reimplement",
  /** Inspecting completed work against its requirements before calling it done. A pass over the finished change measured against what was asked, before it is presented as complete. */
  reviewBeforeFinal: "review-before-final",
  /** Correctness under ordinary failure and boundary conditions. Behavior that holds at the edges the code will really meet: empty input, a failed call, a value at its limit. */
  robustness: "robustness",
  /** Output labelled with the role that produced or reviewed it. Reviewer evidence distinguishable from implementation output, so a reader knows which agent is speaking. */
  roleAttributedOutput: "role-attributed-output",
  /** Approval without substantive review. A verdict issued without checking the requirements or the evidence — the shape of a review with none of its value. */
  rubberStampReview: "rubber-stamp-review",
  /** Expanding past what was asked. The adjacent fix, the nearby cleanup, the improvement nobody requested — work that grows the change beyond its agreed boundary. */
  scopeCreep: "scope-creep",
  /** Revealing, copying, uploading, or moving secrets. Credentials, tokens, or key material leaving where they were held — pasted into output, written to a new file, sent to a service. */
  secretExfiltration: "secret-exfiltration",
  /** Permission handling, injection risk, and unsafe data exposure. Behavior where the failure mode is a boundary crossed: unvalidated input reaching an interpreter, data readable by whoever should not read it. */
  security: "security",
  /** Adapting around a contradicted plan without recording it. A plan that could not be followed as written, quietly reinterpreted, so the record no longer describes what happened. */
  silentDeviation: "silent-deviation",
  /** Observations naming the affected behavior, artifact, or location. A statement someone can go and check, rather than general advice that fits any codebase equally. */
  specific: "specific",
  /** A guess presented as fact. An assertion whose evidence was never established, stated in the same register as one that was. */
  speculativeClaim: "speculative-claim",
  /** Assumptions made visible beside the claims they support. What was taken as given when context was missing, said plainly and near the conclusion resting on it. */
  stateAssumptions: "state-assumptions",
  /** Cosmetic feedback where no style review was asked for. Naming, formatting, and arrangement preferences raised in place of substantive findings. */
  styleOnly: "style-only",
  /** Subjective preference treated as a blocking defect. A judgement about how something reads, given the weight of a correctness, safety, or trust problem. */
  tasteOnlyBlocking: "taste-only-blocking",
  /** Coverage, assertions, uncovered branches, and stale tests. Whether the tests actually establish what they appear to: missing assertions, branches nothing exercises, tests that no longer match the code. */
  tests: "tests",
  /** Network access without explicit allowance. Reaching outside the machine when the user or host policy has not permitted it — fetching, publishing, or calling a remote service. */
  unapprovedNetwork: "unapproved-network",
  /** Refinement with no stop condition. A repair cycle whose end depends on something outside itself, rather than on stated acceptance criteria or a declared bound. */
  unboundedLoop: "unbounded-loop",
  /** Changing code outside the requested change. Restructuring that was not asked for, mixed into a diff whose reviewer expected only the requested work. */
  unrequestedRefactor: "unrequested-refactor",
  /** Commands that can destroy data or alter system state. Invocations whose effects reach past the working tree, or past what can be undone, without the user having agreed to them. */
  unsafeCommand: "unsafe-command",
  /** The user-visible consequence of a finding. What the defect costs the person using the software, stated alongside what it is technically. */
  userImpact: "user-impact",
  /** An agreed draft executed exactly, with departures recorded. The approved plan followed as written, and any point where reality forced a change written down rather than absorbed silently. */
  verbatimExecution: "verbatim-execution",
  /** The task restated as a condition that can be checked. A target established before the work starts — a test that fails now, a command that must exit clean — rather than a judgement made about it afterwards. */
  verifiableGoal: "verifiable-goal",
  /** Whether changed behavior is covered by anything. Tests, examples, or acceptance criteria that actually exercise what changed — and a stated gap when nothing does. */
  verifyCoverage: "verify-coverage",
  /** Loosening a test instead of repairing the implementation. An assertion relaxed, skipped, or deleted so a change goes green, where the change was what broke it. */
  weakenTestsToPass: "weaken-tests-to-pass",
} as const satisfies Record<string, IntentBuiltIn>;

export type AgentTemplateName = "worker" | "reviewer" | "planner" | "oracle" | "searcher";
export type AgentModelTier = "top" | "fast";

export interface AgentTemplateDefinition {
  readonly description: string;
  readonly summary: string;
  readonly modelTier?: AgentModelTier;
}

export const agentTemplates = {
  worker: { description: "Completes assigned work and produces the requested outputs.", summary: "Execution role." },
  reviewer: { description: "Reviews assigned work against its requirements and reports actionable findings.", summary: "Review role." },
  planner: { description: "Structures assigned work into a clear, actionable plan.", summary: "Planning role." },
  oracle: { description: "Provides high-quality consultation for difficult decisions without owning execution.", summary: "Top-tier consultation role.", modelTier: "top" },
  searcher: { description: "Retrieves and summarizes relevant information without modifying the workspace.", summary: "Fast read-only retrieval role.", modelTier: "fast" },
} as const satisfies Record<AgentTemplateName, AgentTemplateDefinition>;

export type ResourceTrigger = "on-activation" | "on-demand";
export const ResourceTrigger = {
  onActivation: "on-activation",
  onDemand: "on-demand",
} as const satisfies Record<string, ResourceTrigger>;

export type ResourceRoot = "package" | "repo";
export const ResourceRoot = {
  package: "package",
  repo: "repo",
} as const satisfies Record<string, ResourceRoot>;

export type ResourceRender = "reference" | "inline";
export const ResourceRender = {
  reference: "reference",
  inline: "inline",
} as const satisfies Record<string, ResourceRender>;

export type Status = "draft" | "ready";
export const Status = {
  draft: "draft",
  ready: "ready",
} as const satisfies Record<string, Status>;

export type Trust = "verified" | "blocked" | "unreviewed";
export const Trust = {
  verified: "verified",
  blocked: "blocked",
  unreviewed: "unreviewed",
} as const satisfies Record<string, Trust>;

export interface CdkDiagnostic {
  readonly severity: "warning" | "error";
  readonly code: string;
  readonly fieldPath: string;
  readonly message: string;
}

export interface SynthPlan {
  readonly delegate: "ctx-traits-wasm-core-or-cli";
  readonly command: readonly string[];
  readonly draft: JsonObject;
  readonly diagnostics: readonly CdkDiagnostic[];
  readonly format: SynthFormat;
  readonly out?: string;
}

export interface RuntimeDelegationPlan {
  readonly surface: RuntimeSurface;
  readonly operation: RuntimeOperation;
  readonly wasmExport?: string;
  readonly cliCommand?: readonly string[];
  readonly request: JsonValue;
  readonly note: "delegates-to-rust-core";
}
// --- Canonical document model (generated from the Rust trait schema) ---

/**
 * A portable abstract agent role declaration.
 */
export type CanonicalAgent = {
  /**
   * Required human-readable role description.
   */
  readonly "description": string;
  /**
   * Role identifier, referenced by sequence items as `agent:<id>`.
   */
  readonly "id": string;
  /**
   * Optional session binding for this agent's frames: `session:<id>`
   * (shared with every other agent bound to the same declared session),
   * or a bare `per-frame`/`persistent` lifecycle value, which is always
   * agent-local and never implies sharing. Omitted preserves legacy
   * configuration-driven behavior during migration; absent both canonical
   * and configured values remains `per-frame`.
   */
  readonly "session"?: string | undefined;
  /**
   * Optional short role summary.
   */
  readonly "summary"?: string | undefined;
  /**
   * Optional standing instructions for this role, delivered through the
   * harness's system-prompt channel once per session rather than repeated
   * in every frame's user message. Holds doctrine the role always obeys —
   * not per-step work, which belongs in the step's own prompt. Model-visible
   * like any other instruction text: compiled into the model view, audited
   * for hidden content, and covered by the canonical digest.
   */
  readonly "system"?: string | undefined;
};

/**
 * `[behavior]` model.
 */
export type CanonicalBehavior = {
  /**
   * Directness level: scalar slug.
   */
  readonly "directness"?: CanonicalGuidanceItem | undefined;
  /**
   * Format descriptors (e.g. "findings-first", "bullets").
   */
  readonly "format"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Initiative: scalar slug.
   */
  readonly "initiative"?: CanonicalGuidanceItem | undefined;
  /**
   * Method descriptors (e.g. "evidence-first").
   */
  readonly "method"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Scope control: scalar slug.
   */
  readonly "scope-control"?: CanonicalGuidanceItem | undefined;
  /**
   * Tone descriptors (e.g. "technical", "direct").
   */
  readonly "tone"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Uncertainty handling: scalar slug.
   */
  readonly "uncertainty"?: CanonicalGuidanceItem | undefined;
  /**
   * Verbosity level: scalar slug.
   */
  readonly "verbosity"?: CanonicalGuidanceItem | undefined;
};

/**
 * One ordered `branch-failure` entry naming a declared branch and its
 * terminal failure policy.
 */
export type CanonicalBranchFailureEntry = {
  readonly "branch": string;
  readonly "on-failure": CanonicalBranchFailurePolicy;
};

/**
 * Per-branch terminal failure policy.
 */
export type CanonicalBranchFailurePolicy = "skip" | "park" | "panel-fail";

/**
 * One declared checklist item: the unit that receives exactly one verdict.
 * 
 * `id` is the item's identity and is stable across rewordings of `text` — a
 * reworded criterion keeps its id and changes its digest, which is what lets
 * a receipt distinguish "this item was answered again" from "this item now
 * asks something else". Deriving an id from `text` would collapse that
 * distinction, so ids are declared, never computed.
 */
export type CanonicalChecklistItem = {
  /**
   * Elaboration presented alongside `text`. Detail is never separately
   * verdict-bearing: one item is one verdict.
   */
  readonly "detail"?: string | undefined;
  /**
   * Item identifier, unique within its checklist.
   */
  readonly "id": string;
  /**
   * Whether a verdict for this item must carry evidence. When any item in
   * a checklist requires it, the synthesized verdict schema makes the
   * `evidence` field required.
   */
  readonly "requires-evidence"?: boolean | undefined;
  /**
   * The criterion as the reviewer reads it.
   */
  readonly "text": string;
};

/**
 * Advanced command declaration table. The source shorthand `cmd = "..."`
 * remains the primary authoring path; this table carries explicit argv when
 * the author needs to avoid string parsing entirely.
 */
export type CanonicalCommandDeclaration = {
  /**
   * Explicit argv. Mutually exclusive with `argv-from`.
   */
  readonly "argv"?: readonly string[] | undefined;
  /**
   * Local `[schema:text]` input port resolved once into concrete argv when
   * the command frame is built. Slots are deliberately unsupported so an
   * agent-produced value cannot select the executable.
   */
  readonly "argv-from"?: string | undefined;
  /**
   * See [`CommandPlan::capture_bytes`].
   */
  readonly "capture-bytes"?: number | undefined;
  /**
   * Optional working directory policy.
   */
  readonly "cwd"?: string | undefined;
  readonly "executable-digest-from"?: string | undefined;
  /**
   * Runtime idle timeout in milliseconds.
   */
  readonly "idle-timeout-ms"?: number | undefined;
  /**
   * Exit codes treated as success. Defaults to `[0]` semantically.
   */
  readonly "success-exit-code"?: readonly number[] | undefined;
  /**
   * Runtime timeout in milliseconds.
   */
  readonly "timeout-ms"?: number | undefined;
};

/**
 * Scalar-or-array string list for composition typed refs.
 * 
 * Authoring accepts a string or an array of strings; canonical serialization
 * is always an array.
 */
export type CanonicalCompositionRefList = readonly string[];

/**
 * A named condition body keyed by `[condition.<id>]`.
 */
export type CanonicalCondition = {
  readonly "all"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "any"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "at-least"?: JsonValue | undefined;
  readonly "at-most"?: JsonValue | undefined;
  readonly "condition"?: string | undefined;
  readonly "count"?: string | undefined;
  readonly "description"?: string | undefined;
  readonly "elapsed-seconds-at-least"?: JsonValue | undefined;
  readonly "empty"?: string | undefined;
  readonly "equals"?: JsonValue | undefined;
  readonly "field"?: string | undefined;
  readonly "field-equals"?: JsonValue | undefined;
  readonly "greater-than"?: JsonValue | undefined;
  readonly "iteration"?: number | undefined;
  readonly "iteration-at-least"?: number | undefined;
  readonly "less-than"?: JsonValue | undefined;
  readonly "not"?: CanonicalGuardExpr | undefined;
  readonly "output"?: string | undefined;
  readonly "present"?: string | undefined;
  readonly "signal"?: string | undefined;
  readonly "slot"?: string | undefined;
};

/**
 * Duplicate-aware map of named conditions keyed by condition ID.
 */
export type CanonicalConditionMap = Readonly<Record<string, CanonicalCondition>>;

/**
 * A `[[relations.conflicts]]` entry: targetless — applies to the declaring
 * trait when `when` matches. Rejects `target`, `required`, `suggested`,
 * `conflicting`, `strength`, `max-depth`, `follows`, and `suppresses`.
 */
export type CanonicalConflicts = {
  readonly "reason": string;
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * The optional `[composition]` section.
 */
export type CanonicalContract = {
  /**
   * Traits or behavior axes that should not co-activate.
   * Accepted ref kinds: `trait`, `behavior`.
   */
  readonly "conflict"?: string | readonly string[] | undefined;
  /**
   * What to do when conflicts are found: `require-decision`,
   * `warn-and-isolate`, `fail-plan`.
   */
  readonly "conflict-policy"?: string | undefined;
  /**
   * How to combine with other traits: `structured`, `isolated`, `render-only`.
   */
  readonly "merge-strategy"?: string | undefined;
};

/**
 * Normalized list of contract ref strings for prompt input/output fields.
 * Accepts scalar-or-array at the decode boundary but always stores a
 * `Vec<String>` — source scalar-vs-array shape is not preserved as semantic
 * state. This type is distinct from [`TargetList`](crate::shared::TargetList)
 * so render target lists and protocol contract refs cannot drift together.
 */
export type CanonicalContractRefList = readonly string[];

/**
 * `ctx.traits` runtime/reporting extensions.
 */
export type CanonicalCtxExtensions = {
  readonly "subagent"?: CanonicalSubagentIntent | undefined;
};

/**
 * The optional `[activation]` section.
 */
export type CanonicalDeclaration = {
  /**
   * Manual activation is declarative data only; later phases gate runtime use.
   */
  readonly "manual"?: boolean | undefined;
  readonly "min-score"?: number | undefined;
  readonly "priority"?: number | undefined;
  /**
   * Ordered rules. Rules compose as OR during scoring.
   */
  readonly "rule"?: readonly CanonicalRule[] | undefined;
};

/**
 * A dependency declaration: alias, trait identity, version, and optional
 * source metadata.
 */
export type CanonicalDependency = {
  /**
   * Typed reference namespace for this dependency (e.g. `"aws"`).
   * 
   * Must be unique within the manifest. Used to qualify refs such as
   * `slot:aws/scope`. Must be a single-segment namespace without `:`, `.`,
   * `/`, or whitespace.
   */
  readonly "alias": string;
  /**
   * Build-derived digest of the dependency content actually consumed
   * (imported) by this canonical. Present only on stamps the build
   * writes for import-based composition (task 0170) — never
   * hand-authored.
   */
  readonly "digest"?: string | undefined;
  /**
   * The trait ID being depended on (e.g. `"ctx/aws-log-primitives"`).
   */
  readonly "id": string;
  /**
   * Optional source metadata. When omitted, the source must be resolved
   * from the package-local `trait.lock` or provided explicitly by the caller.
   */
  readonly "source"?: JsonValue | undefined;
  /**
   * The trait version (e.g. `"0.1.0"`).
   */
  readonly "version": string;
};

/**
 * Required agent+user prose: the single model-visible description of what
 * the trait/variant does. Rendered in the model view opening section, the
 * frame `<description>` tag, and listings.
 */
export type CanonicalDescription = string;

/**
 * A typed digest value in `sha256:<hex>` format.
 */
export type CanonicalDigest = string;

/**
 * An `[[eval]]` declaration: a declared product evaluation check.
 * 
 * Eval declarations describe checks that can be run against a trait. They do
 * not execute by themselves. The `input` and `output` fields are product
 * refs (e.g. `render:agent-skills`, `fixture:fixtures/example.md`,
 * `trait:self`, `report:scenario-shape`), not repository test fixtures.
 */
export type CanonicalEval = {
  /**
   * Stable eval identifier (e.g. `"agent-skills-render"`).
   */
  readonly "id": string;
  /**
   * What the eval consumes (e.g. `render:agent-skills`, `trait:self`,
   * `fixture:fixtures/example.md`).
   */
  readonly "input"?: string | undefined;
  /**
   * Expected fixture, report, or comparison output (e.g.
   * `fixture:fixtures/example.md`, `report:scenario-shape`).
   */
  readonly "output"?: string | undefined;
  /**
   * Scenario IDs this eval covers (references to `[[scenario]]` IDs).
   * 
   * Canonical authoring uses singular `scenario` (scalar-or-array):
   * `scenario = "happy-path"` or
   * `scenario = ["happy-path", "edge-case"]`.
   */
  readonly "scenario"?: readonly string[] | undefined;
  /**
   * Eval/check type.
   */
  readonly "variant": CanonicalEvalVariant;
};

/**
 * The variant of an eval declaration.
 * 
 * MVP variants (`documentation`, `lint`, `golden-render`) have initial
 * implementation paths. Future variants (`behavioral`, `runtime`) are
 * declared but may be unsupported for execution.
 */
export type CanonicalEvalVariant = "documentation" | "lint" | "golden-render" | "behavioral" | "runtime";

/**
 * A loop's `on-exhausted` declaration: the keywords `"continue"`/`"abort"`,
 * or one or more signal refs emitted when the loop continues past
 * exhaustion. A one-element sequence collapses to `One` on decode so each
 * meaning has exactly one canonical spelling.
 */
export type CanonicalExhaustionTarget = string | readonly string[];

/**
 * Top-level non-standard extensions namespace.
 */
export type CanonicalExtensions = {
  readonly "ctx"?: CanonicalCtxExtensions | undefined;
};

/**
 * Closed recovery-route declaration.
 */
export type CanonicalFailureRoute = {
  readonly "signal"?: string | undefined;
  readonly "step": string;
};

/**
 * A control failure either emits a legacy signal or abandons the current path
 * and schedules a later top-level recovery step.
 */
export type CanonicalFailureTarget = string | CanonicalFailureRoute;

/**
 * One guard expression. A string ref is either `signal:<id>` or
 * `condition:<id>`. An array is OR/any composition.
 */
export type CanonicalGuardExpr = string | readonly CanonicalGuardExpr[] | CanonicalGuardPredicate;

/**
 * Inline guard predicate form.
 */
export type CanonicalGuardPredicate = {
  readonly "all"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "any"?: readonly CanonicalGuardExpr[] | undefined;
  readonly "at-least"?: JsonValue | undefined;
  readonly "at-most"?: JsonValue | undefined;
  readonly "condition"?: string | undefined;
  readonly "count"?: string | undefined;
  /**
   * Cumulative active-drive elapsed seconds (runtime-supplied evidence,
   * never a core wall clock) at least this threshold. Threshold is a JSON
   * number or a `{ ref = "slot:..."/"port:..." }` numeric reference.
   */
  readonly "elapsed-seconds-at-least"?: JsonValue | undefined;
  readonly "empty"?: string | undefined;
  readonly "equals"?: JsonValue | undefined;
  readonly "field"?: string | undefined;
  /**
   * Filters `count` to elements whose `field` equals this value. Paired
   * with `field`; meaningless alone. Kept distinct from `equals`, which is
   * already the count's threshold — one predicate needs both a "which
   * elements" and a "how many", and they cannot share a spelling.
   */
  readonly "field-equals"?: JsonValue | undefined;
  readonly "greater-than"?: JsonValue | undefined;
  readonly "iteration"?: number | undefined;
  readonly "iteration-at-least"?: number | undefined;
  readonly "less-than"?: JsonValue | undefined;
  readonly "not"?: CanonicalGuardExpr | undefined;
  readonly "output"?: string | undefined;
  /**
   * Presence-aware leaf (schema-version `"0.3"` only). Bare form is a local
   * optional input `port:*`; with `field`, a declared optional field of a
   * local `port:*`/`slot:*` object container. Yields `Matched`/`NotMatched`/`Unmeasurable`
   * tri-state internally; only `Matched` routes `true`.
   */
  readonly "present"?: string | undefined;
  readonly "signal"?: string | undefined;
  readonly "slot"?: string | undefined;
};

/**
 * A slug-identified guidance item with optional local render text.
 */
export type CanonicalGuidanceItem = {
  readonly "description"?: string | undefined;
  readonly "id": CanonicalSlug;
  readonly "summary"?: string | undefined;
};

/**
 * Scalar-or-array guidance list. Strings normalize to slug-only items.
 */
export type CanonicalGuidanceItemList = readonly CanonicalGuidanceItem[];

/**
 * Stable, durable trait identifier (not a display name).
 * 
 * Must be non-empty and use only lowercase letters, digits, and hyphens.
 * Display names and search labels are separate fields.
 */
export type CanonicalId = string;

/**
 * `[intent]` model.
 */
export type CanonicalIntent = {
  /**
   * Things to avoid doing.
   */
  readonly "avoid"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Things that must never happen.
   */
  readonly "block"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Areas to focus attention on.
   */
  readonly "focus"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
  /**
   * Required outcomes or actions.
   */
  readonly "require"?: CanonicalGuidanceItem | readonly CanonicalGuidanceItem[] | undefined;
};

/**
 * Closed, policy-discriminated barrier join for a `parallel` sequence item.
 * Omission on `SequenceItem.join` is behaviorally identical to
 * `{ policy = "collect-in-order" }` — the P263 barrier.
 */
export type CanonicalJoinPolicy = {
  readonly "policy": "collect-in-order";
} | {
  readonly "destination": string;
  readonly "operation": CanonicalWriteOperation;
  readonly "policy": "reduce-merge";
  readonly "source": string;
} | {
  readonly "destination": string;
  readonly "guard": CanonicalGuardExpr;
  readonly "policy": "quorum-verdict";
  readonly "source": string;
};

/**
 * `[metadata]` facets: family, variant, job, domain, artifact, audience,
 * environment, tag.
 * 
 * All facets use kebab-case slug strings with scalar-or-array authoring.
 * Slug validation happens in the post-decode taxonomy pass. `family` and
 * `variant` are display-only: they never drive activation or canonical
 * trait resolution. Since P451, a declared `variant` additionally selects
 * which `[agent.variant.<v>.role.*]` config qualifier a run resolves
 * against (config routing, not activation or canonical resolution — see
 * `ctx_traits_io::harness_config::resolve_run_variant`).
 */
export type CanonicalMetadata = {
  readonly "artifact"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "audience"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "domain"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "environment"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Declared family identity for list grouping and consistency
   * advisories against the trait package ID. Display-only.
   */
  readonly "family"?: CanonicalSlug | undefined;
  readonly "job"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  readonly "tag"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Declared variant identity within `family`. Display-only.
   */
  readonly "variant"?: CanonicalSlug | undefined;
};

/**
 * Human-readable display name, not a durable identifier.
 */
export type CanonicalName = string;

/**
 * A named sequence block keyed by `[sequence.<id>]`.
 */
export type CanonicalNamedSequence = {
  /**
   * Human-readable description of the sequence block.
   */
  readonly "description"?: string | undefined;
  /**
   * Ordered items in this sequence block.
   */
  readonly "sequence"?: readonly CanonicalSequenceItem[] | undefined;
};

/**
 * Duplicate-aware map of named sequences keyed by sequence ID.
 */
export type CanonicalNamedSequenceMap = Readonly<Record<string, CanonicalNamedSequence>>;

/**
 * A step output sink.
 * 
 * Existing manifests serialize a plain typed ref string. New authoring may use
 * an inline table for slot write operations, e.g.
 * `{ slot = "slot:notes", operation = "append" }`, or may mark a slot sink
 * optional (`{ slot = "slot:notes", optional = true }`, P105): an optional
 * sink never gates step acceptance, and its absence at step completion is a
 * signed non-failure rather than a missing-output rejection — the output-side
 * mirror of [`SequenceInput::OptionalSlot`].
 */
export type CanonicalOutputSink = string | {
  readonly "operation"?: CanonicalWriteOperation | undefined;
  readonly "optional"?: boolean | undefined;
  readonly "slot": string;
};

/**
 * Normalized list of sequence output sinks.
 */
export type CanonicalOutputSinkList = readonly CanonicalOutputSink[];

/**
 * A `[[port]]` declaration: a boundary contract.
 */
export type CanonicalPort = {
  /**
   * Optional runtime default source for input ports. Static render/check do
   * not execute it; CLI/IO runtime may use it only with explicit permission.
   */
  readonly "default"?: CanonicalPortDefault | undefined;
  /**
   * Human-readable description.
   */
  readonly "description": string;
  /**
   * Whether this is an input or output port.
   */
  readonly "direction": CanonicalPortDirection;
  /**
   * Advisory guidance about the value: examples or constraints for whoever
   * supplies it. Metadata only — the schema stays the validation contract.
   * The same field a slot carries, for the same reason.
   */
  readonly "hint"?: string | undefined;
  /**
   * Port identifier (e.g. `"user-prompt"`, `"finding"`).
   */
  readonly "id": string;
  /**
   * Whether this port is optional. Defaults to `false`.
   */
  readonly "optional"?: boolean | undefined;
  /**
   * Schema ref (e.g. `"schema:text"`, `"schema:scope"`).
   */
  readonly "schema": string;
  /**
   * Optional display title.
   */
  readonly "title"?: string | undefined;
  /**
   * For output ports: the slot ref that exposes the value (`"slot:<id>"`).
   * Input ports must not declare `value`.
   */
  readonly "value"?: string | undefined;
};

/**
 * Runtime default source for an input port.
 */
export type CanonicalPortDefault = {
  readonly "command"?: CanonicalPortDefaultCommand | undefined;
  readonly "value"?: string | undefined;
};

/**
 * Command-backed runtime default source for an input port.
 */
export type CanonicalPortDefaultCommand = {
  readonly "argv"?: readonly string[] | undefined;
  readonly "capture"?: string | undefined;
  /**
   * Runtime stdout capture ceiling in bytes. Absent uses the IO host's
   * documented default-input capture ceiling. A capture that exceeds this
   * fails the run rather than landing a truncated value in the port.
   */
  readonly "capture-bytes"?: number | undefined;
  readonly "cmd"?: string | undefined;
  readonly "cwd"?: string | undefined;
  /**
   * Runtime timeout in milliseconds. Absent uses the IO host's documented
   * default-input timeout.
   */
  readonly "timeout-ms"?: number | undefined;
};

/**
 * Port direction: input or output.
 */
export type CanonicalPortDirection = "input" | "output";

/**
 * Scalar-or-array string list for activation predicates.
 * 
 * Authoring accepts either a string or an array of strings; canonical
 * serialization is always an array.
 */
export type CanonicalPredicateList = readonly string[];

/**
 * A `[procedure]` section: deterministic sequence orchestration.
 * 
 * Optional top-level section. When present, `description` must be non-empty
 * and `sequence` must be non-empty. The `input` and `output` contract fields
 * declare procedure-level boundary ports. `sequence` holds inline
 * `[[procedure.sequence]]` items, in the order they run.
 */
export type CanonicalProcedure = {
  /**
   * Human-readable description of what the procedure accomplishes.
   */
  readonly "description": string;
  /**
   * Model-level input refs (e.g. `port:user-prompt`, `slot:scope`).
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Model-level output refs (e.g. `port:finding`, `slot:result`).
   */
  readonly "output"?: string | readonly string[] | undefined;
  /**
   * Ordered `[[procedure.sequence]]` items. Definition order is execution
   * order.
   */
  readonly "sequence"?: readonly CanonicalSequenceItem[] | undefined;
};

/**
 * Normalized list of ref strings for procedure `input`, `output`, and
 * `sequence` fields.
 * 
 * Accepts scalar-or-array at the decode boundary but always stores a
 * `Vec<String>`. Distinct from
 * [`ContractRefList`](crate::trait::prompt::ContractRefList) so procedure
 * contracts remain independent.
 */
export type CanonicalProcedureRefList = readonly string[];

/**
 * One ordered write in a closed `project` sequence item.
 * 
 * Runtime reads every slot source from one pre-step snapshot, optionally
 * selects one top-level object field, validates every destination write,
 * then commits all writes atomically. A literal source (P431) is a canonical
 * value declared on the projection itself rather than read from a slot;
 * literal-backed projections contribute no sequence input and reject
 * `field`. Destinations are local typed slots; `replace`, `append`, and
 * `increment` are the supported operations.
 */
export type CanonicalProjection = {
  readonly "destination": string;
  readonly "field"?: string | undefined;
  readonly "operation"?: CanonicalWriteOperation | undefined;
  readonly "source": CanonicalProjectionSource;
};

/**
 * One `procedure.sequence[].projection[].source`: either an existing local
 * slot ref, or a canonical typed literal wrapped as `{ literal = <value> }`.
 * The wrapper keeps the literal form unambiguous with the plain string
 * slot-ref shape — an unwrapped string literal would be indistinguishable
 * from `source = "slot:..."`.
 */
export type CanonicalProjectionSource = string | {
  readonly "literal": JsonValue;
};

/**
 * A `[prompt.<id>]` body: inline text or resource source plus contracts.
 * 
 * The prompt ID is the map key in `Trait.prompts`, not a field on this
 * struct.
 */
export type CanonicalPrompt = {
  /**
   * Human-readable description.
   */
  readonly "description"?: string | undefined;
  /**
   * Required input refs for this prompt (e.g. `port:user-prompt`,
   * `slot:scope`, `resource:checklist`). Accepts scalar-or-array,
   * normalized to a flat list.
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Output contract refs — local `slot:<id>` refs only. Accepts
   * scalar-or-array, normalized to a flat list.
   */
  readonly "output"?: string | readonly string[] | undefined;
  /**
   * Resource-backed prompt body source (`resource:<id>`).
   */
  readonly "source"?: string | undefined;
  /**
   * The prompt body text. May contain typed ref interpolations like
   * `{port:user-prompt}` or `{slot:scope}`.
   */
  readonly "text"?: string | undefined;
};

/**
 * A map of prompt IDs to prompt bodies that rejects duplicate keys at decode
 * time rather than silently overwriting.
 * 
 * This wraps [`BTreeMap<String, Prompt>`] with a custom `Deserialize` that
 * detects duplicate keys and returns an error before collapsing them.
 */
export type CanonicalPromptMap = Readonly<Record<string, CanonicalPrompt>>;

/**
 * A parsed canonical typed reference: `<kind>:<path>`.
 * 
 * The path is preserved verbatim from the source text. [`Self::ref_path`]
 * decomposes it into namespace and id for dependency-qualified refs.
 * `Display` round-trips to the canonical accepted text.
 */
export type CanonicalReference = string;

/**
 * The optional `[relations]` section.
 */
export type CanonicalRelations = {
  readonly "conflicts"?: readonly CanonicalConflicts[] | undefined;
  readonly "requires"?: readonly CanonicalRequires[] | undefined;
  readonly "suggests"?: readonly CanonicalSuggests[] | undefined;
};

/**
 * Scalar-or-array typed reference list for `when` conditions.
 */
export type CanonicalRelationsRefList = readonly CanonicalReference[];

/**
 * A `[[relations.requires]]` entry: the source needs the target.
 */
export type CanonicalRequires = {
  /**
   * Required explanation.
   */
  readonly "reason": string;
  /**
   * Required target: `port:*` or `trait:*`.
   */
  readonly "target": CanonicalReference;
  /**
   * Conditions that enable this relation: `rule:*` or `signal:*` refs.
   * Entries in one `when` list are AND; multiple entries model OR.
   */
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * An `[[resource]]` declaration: an external blob reference or inline text.
 * 
 * File-backed resources are materialized from IO evidence. Inline content is
 * materialized entirely within core without filesystem access.
 */
export type CanonicalResource = {
  /**
   * Inline resource body. Inline resources require no host IO.
   */
  readonly "content"?: string | undefined;
  /**
   * The digest of this resource's file bytes, in `sha256:<hex>` form.
   * 
   * COMPUTED at build time, never authored: `ctx traits build` reads the
   * file and writes this. It sat here before as a hand-typed pin, which is
   * why nothing ever carried one — an author had to paste a hex string
   * that went stale on the next legitimate edit.
   * 
   * It lives in the canonical rather than the lock because it has to
   * travel with the resource that declares it. Evidence kept anywhere else
   * gets separated from the bytes it describes: a package materialized
   * into the built-in store, vendored into a consumer, or written by hand
   * each loses it a different way, and the verifier then has nothing to
   * compare against.
   * 
   * The cost is deliberate. Editing a protected resource changes the
   * trait's canonical digest, which moves this machine's trust decision to
   * unreviewed — correct, because a resource is content a model reads, and
   * changing it changes what the trait does.
   */
  readonly "digest"?: CanonicalDigest | undefined;
  /**
   * Advisory hint about the resource contents or usage.
   */
  readonly "hint"?: string | undefined;
  /**
   * Resource identifier (e.g. `"scope-schema"`).
   */
  readonly "id": string;
  /**
   * Typed inputs required by a resource template.
   */
  readonly "input"?: string | readonly string[] | undefined;
  /**
   * Declared checklist items. Valid only alongside `variant = "checklist"`,
   * where they replace `path`/`content` as the resource body: the items are
   * canonical and the presented text is rendered from them, so no prose
   * copy of the checklist can drift from the typed one.
   */
  readonly "item"?: readonly CanonicalChecklistItem[] | undefined;
  /**
   * Path to the resource blob, relative to `root`.
   */
  readonly "path"?: string | undefined;
  /**
   * Whether this resource's bytes are verified against `digest`.
   * 
   * `None` means "derive from `root`", which is what almost every
   * declaration wants: a package-owned resource ships with the trait, so
   * its bytes are the trait's own and are verified; a `root = "repo"`
   * resource is an input the consuming project supplies — a task board
   * differs in every repository and changes between runs — so there is
   * nothing stable to verify it against.
   * 
   * Set it explicitly only to disagree: `false` on a package resource that
   * legitimately churns.
   */
  readonly "protected"?: boolean | undefined;
  /**
   * How this resource's body is presented to the model. Defaults to
   * `reference` for path-backed resources and `inline` for content or
   * checklist resources (see `effective_render()`); omitted from
   * canonical serialization when unset, so existing declarations stay
   * byte-identical.
   */
  readonly "render"?: CanonicalResourceRender | undefined;
  /**
   * Which root the declared `path` is relative to. Defaults to `package`
   * and is omitted from canonical serialization when default, so existing
   * package-relative declarations stay byte-identical.
   */
  readonly "root"?: CanonicalResourceRoot | undefined;
  /**
   * When to load the resource at runtime.
   */
  readonly "trigger"?: CanonicalResourceTrigger | undefined;
  /**
   * Optional resource kind. `template` resources may declare typed inputs.
   */
  readonly "variant"?: string | undefined;
};

/**
 * Normalized typed-ref inputs for resource templates.
 */
export type CanonicalResourceInputList = readonly string[];

export type CanonicalResourceRender = ResourceRender;

export type CanonicalResourceRoot = ResourceRoot;

export type CanonicalResourceTrigger = ResourceTrigger;

/**
 * One `[[activation.rule]]` declaration.
 */
export type CanonicalRule = {
  readonly "exclude-file-glob"?: CanonicalPredicateList | undefined;
  readonly "exclude-keyword"?: CanonicalPredicateList | undefined;
  readonly "explicit-phrase"?: CanonicalPredicateList | undefined;
  readonly "file-glob"?: CanonicalPredicateList | undefined;
  /**
   * Stable rule ID. Required and unique within `[activation]`.
   */
  readonly "id"?: string | undefined;
  readonly "language"?: CanonicalPredicateList | undefined;
  /**
   * Preferred initial load level: `discovery`, `summary`, or `full`.
   */
  readonly "load-level"?: string | undefined;
  readonly "mode"?: CanonicalPredicateList | undefined;
  /**
   * Human-readable reason shown by explanation surfaces.
   */
  readonly "reason"?: string | undefined;
  readonly "signal"?: CanonicalPredicateList | undefined;
  readonly "task-keyword"?: CanonicalPredicateList | undefined;
  readonly "weight"?: number | undefined;
};

/**
 * A `[[scenario]]` declaration: a product review behavior example.
 * 
 * Scenarios are behavior hints/specifications for humans, renderers, lint
 * checks, prompt review, and future behavioral eval harnesses. They are not
 * proof by themselves.
 */
export type CanonicalScenario = {
  /**
   * Stable scenario identifier (e.g. `"rust-review-positive"`).
   */
  readonly "id": string;
  /**
   * Example task or prompt input.
   */
  readonly "input"?: string | undefined;
  /**
   * Expected result, refusal, warning, or behavior description.
   */
  readonly "output"?: string | undefined;
  /**
   * Optional advisory tags for filtering or grouping.
   * 
   * Canonical authoring uses singular `tag` (scalar-or-array):
   * `tag = "security"` or `tag = ["security", "rust"]`.
   */
  readonly "tag"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Behavior variant: positive, negative, or edge.
   */
  readonly "variant": CanonicalScenarioVariant;
};

/**
 * The behavioral variant of a scenario.
 */
export type CanonicalScenarioVariant = "positive" | "negative" | "edge";

/**
 * A `[[schema]]` declaration: a named schema contract.
 * 
 * Must have exactly one of `resource`, `fields`, or scalar `schema`.
 */
export type CanonicalSchemaDeclaration = {
  /**
   * Closed set of allowed scalar values for scalar enum schemas.
   */
  readonly "allowed"?: readonly JsonValue[] | undefined;
  /**
   * Human-readable description of the schema.
   */
  readonly "description"?: string | undefined;
  /**
   * Inline field declarations for duck-typed compatibility.
   * Mutually exclusive with `resource`.
   */
  readonly "fields"?: Readonly<Record<string, CanonicalSchemaField>> | undefined;
  /**
   * Schema identifier (e.g. `"scope"`).
   */
  readonly "id": string;
  /**
   * Resource ref: `resource:<id>` pointing to an opaque blob.
   * Mutually exclusive with `fields`.
   */
  readonly "resource"?: string | undefined;
  /**
   * Scalar schema ref for closed-value enum schemas.
   * Mutually exclusive with `resource` and `fields`.
   */
  readonly "schema"?: string | undefined;
};

/**
 * One inline field declaration for duck-typed schema compatibility.
 */
export type CanonicalSchemaField = {
  /**
   * Optional closed set of allowed scalar values for this field.
   */
  readonly "allowed"?: readonly JsonValue[] | undefined;
  /**
   * Human-readable description.
   */
  readonly "description"?: string | undefined;
  /**
   * Advisory hint.
   */
  readonly "hint"?: string | undefined;
  /**
   * Whether this field is required.
   */
  readonly "required"?: boolean | undefined;
  /**
   * Field schema ref (e.g. `"schema:text"`, `"schema:number"`).
   */
  readonly "schema": string;
};

export type CanonicalSchemaForm = SchemaForm;

/**
 * Trait schema version string (e.g. "0.2").
 */
export type CanonicalSchemaVersion = string;

/**
 * Semantic version text (e.g. "0.1.0").
 */
export type CanonicalSemanticVersion = string;

/**
 * One `procedure.sequence[].input` entry.
 * 
 * An ordinary entry is a plain typed ref string (`port:*`, `slot:*`,
 * `resource:*`). A resource ref may additionally carry a `when` guard,
 * authored as `{ ref = "resource:<id>", when = <GuardExpr> }`; the runtime
 * includes that resource in the step's available context and
 * `resource_evidence` only when the guard matches at readiness. A slot ref
 * may instead be authored as `{ slot = "slot:<id>", optional = true }`
 * (P447): that slot never gates validation, planning, recovery, or runtime
 * readiness, and is omitted from the frame entirely until an accepted value
 * exists. Port inputs and plain (non-decorated) slot inputs remain
 * unconditional.
 */
export type CanonicalSequenceInput = string | {
  readonly "ref": string;
  readonly "when": CanonicalGuardExpr;
} | {
  readonly "optional": boolean;
  readonly "slot": string;
};

/**
 * Normalized list of `procedure.sequence[].input` entries.
 * 
 * Accepts scalar-or-array at the decode boundary, where each element is a
 * plain ref string, a guarded-resource table, or an optional-slot table
 * (P447). Always stores a `Vec<SequenceInput>`.
 */
export type CanonicalSequenceInputList = readonly CanonicalSequenceInput[];

/**
 * A `[[procedure.sequence]]` item: one item in the procedure, owned by the
 * procedure rather than by a separate top-level table.
 * 
 * `[[procedure.sequence]]` definition order is the default execution order.
 * An optional `id` names the item for references and evidence.
 */
export type CanonicalSequenceItem = {
  /**
   * Loop terminal guard.
   */
  readonly "abort-if"?: CanonicalGuardExpr | undefined;
  /**
   * Optional abstract agent role that should serve this executable item.
   */
  readonly "agent"?: string | undefined;
  /**
   * `parallel` ordered per-branch terminal failure policy. A branch with
   * no entry defaults to `panel-fail`.
   */
  readonly "branch-failure"?: readonly CanonicalBranchFailureEntry[] | undefined;
  /**
   * Ordered, author-order list of local `sequence:<id>` refs run as
   * independent branches of a `kind = "parallel"` item. Never sorted.
   */
  readonly "branches"?: string | readonly string[] | undefined;
  /**
   * See [`CommandPlan::capture_bytes`], for simple `cmd` shorthand.
   */
  readonly "capture-bytes"?: number | undefined;
  /**
   * Simple no-shell command shorthand for a command-backed sequence item.
   */
  readonly "cmd"?: string | undefined;
  /**
   * Explicit command declaration. `cmd` and `command` are mutually
   * exclusive source forms and lower to the same command plan.
   */
  readonly "command"?: CanonicalCommandDeclaration | undefined;
  /**
   * `for-each` concurrency request. Additive: `false`/absent is byte-identical
   * to documents authored before concurrency existed.
   */
  readonly "concurrent"?: boolean | undefined;
  /**
   * Optional format preferences. Accepted as a format-preference declaration on prompt/command items; rejected on control items.
   */
  readonly "format"?: CanonicalSlug | readonly CanonicalSlug[] | undefined;
  /**
   * Optional stable identifier for references and run evidence.
   */
  readonly "id"?: string | undefined;
  /**
   * Runtime idle timeout in milliseconds, for simple `cmd` shorthand.
   */
  readonly "idle-timeout-ms"?: number | undefined;
  /**
   * Input refs (e.g. `port:user-prompt`, `slot:scope`, `resource:data`).
   * A resource entry may additionally be authored as a guarded table
   * (`{ ref = "resource:<id>", when = <GuardExpr> }`); the runtime
   * includes it in this step's frame only when the guard matches.
   */
  readonly "input"?: CanonicalSequenceInput | readonly CanonicalSequenceInput[] | undefined;
  /**
   * `for-each` per-item slot ref.
   */
  readonly "item"?: string | undefined;
  /**
   * `parallel` barrier join policy. Omitted is behaviorally identical to
   * `{ policy = "collect-in-order" }` (P263 barrier).
   */
  readonly "join"?: CanonicalJoinPolicy | undefined;
  /**
   * Explicit item kind. When omitted, `prompt`, `cmd`, and `command` fields
   * provide the current authoring sugar for prompt/command inference.
   */
  readonly "kind"?: CanonicalSequenceKind | undefined;
  /**
   * Required positive upper bound on `branches` length for a `parallel`
   * item. `branches.len()` must not exceed this bound.
   */
  readonly "max-branches"?: number | undefined;
  /**
   * Required `for-each` bound.
   */
  readonly "max-items"?: number | undefined;
  /**
   * Required loop bound.
   */
  readonly "max-iterations"?: number | undefined;
  /**
   * Local `schema:integer` input port resolved once at loop entry and frozen
   * into the runtime control frame. Mutually exclusive with
   * `max-iterations`.
   */
  readonly "max-iterations-from"?: string | undefined;
  /**
   * `kind = "terminal"`: rendered headline template, evaluated through
   * the deterministic projection path (never an agent frame).
   */
  readonly "message"?: string | undefined;
  /**
   * Names the signal(s) to emit when `abort-if` is the arm that halts the
   * loop, so the trait's own terminal reason (e.g.
   * `recurring-blocker-unresolved`) is distinguishable from exhaustion in
   * the ledger, the receipt, and `run-status` — the runtime still reports
   * the accurate mechanism (`abort-if-matched`) alongside it. Requires
   * `abort-if`; the `"continue"`/`"abort"` keywords are meaningless here
   * (an `abort-if` match always halts the loop) and are rejected.
   */
  readonly "on-abort"?: CanonicalExhaustionTarget | undefined;
  /**
   * Declared signal refs this item may emit, either directly as refs or
   * derived from deterministic output predicates. On a for-each item this
   * is instead the completion signal, emitted once (at most one entry
   * allowed there).
   */
  readonly "on-complete"?: readonly CanonicalSignalEmissionRule[] | undefined;
  /**
   * Loop exhaustion policy: `"continue"` (the default when omitted),
   * `"abort"`, or one or more `signal:<id>` refs.
   * 
   * Continuing treats exhaustion as a normal outcome — the sequence
   * proceeds to the next item, and any declared signals are emitted as
   * recorded evidence a later guard may read (or ignore). Spending a
   * bounded budget without matching `until` means the work is unfinished,
   * which the following step is responsible for reading; it does not mean
   * the run is broken.
   * 
   * `"abort"` stops the run at exhaustion, for procedures where an unmet
   * exit condition invalidates every step after the loop; no signal is
   * emitted in that case. A run started with strict loops aborts every
   * loop regardless of its declared policy, and suppresses signal
   * emission even when the declaration names one.
   */
  readonly "on-exhausted"?: CanonicalExhaustionTarget | undefined;
  /**
   * Legacy failure signal or structured forward recovery route.
   */
  readonly "on-failure"?: CanonicalFailureTarget | undefined;
  /**
   * Optional named sequence ref selected when a branch guard is false.
   */
  readonly "otherwise"?: string | undefined;
  /**
   * `kind = "terminal"`: success or error. Required on a terminal item.
   */
  readonly "outcome"?: CanonicalTerminalOutcome | undefined;
  /**
   * Output sinks (e.g. `port:finding`, `slot:result`, `schema:verdict`, or
   * `{ slot = "slot:notes", operation = "append" }`).
   */
  readonly "output"?: CanonicalOutputSink | readonly CanonicalOutputSink[] | undefined;
  /**
   * `for-each` list slot ref.
   */
  readonly "over"?: string | undefined;
  /**
   * `kind = "terminal"`: ordered writes for the exit's typed record. An
   * `error` outcome writes the reserved error-record output port; a
   * `success` outcome binds declared output ports named by `destination`.
   * Reuses the ordinary `Projection`/`ProjectionSource` shapes rather than
   * a second projection encoding.
   */
  readonly "payload"?: readonly CanonicalProjection[] | undefined;
  /**
   * Ordered deterministic writes for `kind = "project"`. All source values
   * are read before any destination is committed.
   */
  readonly "projection"?: readonly CanonicalProjection[] | undefined;
  /**
   * Prompt ref (`prompt:<id>`) or inline prompt text.
   */
  readonly "prompt"?: string | undefined;
  /**
   * Named sequence ref (`sequence:<id>`) for sequence/loop/for-each items.
   */
  readonly "sequence"?: string | undefined;
  /**
   * Exit codes treated as success for simple `cmd` shorthand.
   */
  readonly "success-exit-code"?: readonly number[] | undefined;
  /**
   * Runtime timeout in milliseconds for simple `cmd` shorthand.
   */
  readonly "timeout-ms"?: number | undefined;
  /**
   * Human-readable title for this sequence step.
   */
  readonly "title"?: string | undefined;
  /**
   * Loop success guard.
   */
  readonly "until"?: CanonicalGuardExpr | undefined;
  /**
   * Branch entry guard. A true guard selects `sequence`.
   */
  readonly "when"?: CanonicalGuardExpr | undefined;
};

/**
 * Sequence item kind. Omitted kind infers prompt or command from authored fields.
 */
export type CanonicalSequenceKind = "prompt" | "command" | "check" | "sequence" | "branch" | "loop" | "for-each" | "parallel" | "ask" | "project" | "terminal";

/**
 * A `[[session]]` declaration: a named, shareable session identity.
 */
export type CanonicalSession = {
  /**
   * Optional human-readable description of what this session is for.
   */
  readonly "description"?: string | undefined;
  /**
   * Session identifier, referenced by agents as `session:<id>`.
   */
  readonly "id": string;
};

/**
 * One `[sink.session-title]` declaration: `effect.session.title(X)`'s
 * canonical projection.
 */
export type CanonicalSessionTitleSink = {
  readonly "input": CanonicalSinkInput;
  readonly "mode": CanonicalSinkMode;
};

/**
 * A `[[setting]]` definition: a typed operator knob.
 * 
 * Declaration only — `default` is the fallback used when no config layer
 * overrides the value; the resolved value at activation is computed
 * elsewhere and never stored on this type.
 */
export type CanonicalSetting = {
  /**
   * Default value used when no config layer overrides it.
   */
  readonly "default": JsonValue;
  /**
   * Human-readable description of what this setting controls.
   */
  readonly "description": string;
  /**
   * Setting identifier (e.g. `"review-rounds"`).
   */
  readonly "id": string;
  /**
   * Inclusive upper bound. Only valid for `schema = "number"`.
   */
  readonly "max"?: number | undefined;
  /**
   * Inclusive lower bound. Only valid for `schema = "number"`.
   */
  readonly "min"?: number | undefined;
  /**
   * Declared scalar kind.
   */
  readonly "schema": CanonicalSettingSchema;
};

/**
 * Declared scalar kind for a setting.
 */
export type CanonicalSettingSchema = "number" | "text" | "boolean";

/**
 * A `[[signal]]` declaration: a named event identity.
 */
export type CanonicalSignal = {
  /**
   * Human-readable description of when this signal fires.
   */
  readonly "description": string;
  /**
   * Signal identifier (e.g. `"needs-tests"`, `"missing-credentials"`).
   */
  readonly "id": string;
};

/**
 * A signal ref or a deterministic signal derivation rule.
 */
export type CanonicalSignalEmissionRule = string | {
  readonly "signal": string;
  readonly "when": CanonicalGuardExpr;
};

/**
 * A sink's declared input: the standard input union, no new value grammar.
 * 
 * `Scalar` covers a literal string, a template string using the prompt
 * interpolation grammar (`{slot:<id>}`), or a bare `slot:<id>` ref — which
 * of those it is (and therefore whether the sink is verbatim or generated)
 * is classified at decode time, not by this shape. `Parts` is an array of
 * slot refs, optionally decorated `{ slot = "slot:<id>", optional = true }`
 * (P447); an array input is always generated.
 */
export type CanonicalSinkInput = string | readonly CanonicalSequenceInput[];

/**
 * How a sink's declared input becomes the applied value.
 * 
 * `Verbatim`: authored text (a literal string or a template) rendered
 * deterministically, with zero model calls. `Generated`: material (a bare
 * slot ref or an array of slot refs) assembled and handed to the host's
 * existing generation path as context, replacing that path's default
 * context. Stored explicitly in canonical even though it is fully derived
 * from the shape of `input` at authoring time, so decoded documents never
 * need to re-derive it.
 */
export type CanonicalSinkMode = "verbatim" | "generated";

/**
 * The closed set of host sinks a trait may declare. One optional field per
 * sink — never an open map — so an unknown sink key is a decode-time
 * error and a duplicate declaration is structurally impossible.
 */
export type CanonicalSinks = {
  readonly "session-title"?: CanonicalSessionTitleSink | undefined;
};

/**
 * A `[[slot]]` definition: a procedure run ledger value contract.
 */
export type CanonicalSlot = {
  /**
   * A value the slot holds before any step writes one, so a first-pass
   * prompt can interpolate it and a counter can start somewhere.
   */
  readonly "default"?: JsonValue | undefined;
  /**
   * Human-readable description of what this slot represents.
   */
  readonly "description"?: string | undefined;
  /**
   * Advisory hint for the expected slot value, examples, or constraints
   * useful to a step prompt. Metadata only — schema remains the validation
   * contract.
   */
  readonly "hint"?: string | undefined;
  /**
   * Slot identifier (e.g. `"finding"`, `"scope"`, `"note-risk"`).
   */
  readonly "id": string;
  /**
   * Whether reading this slot blocks. A slot is written by a step, so a
   * read before any step could have written is normally refused; an
   * optional slot says otherwise once, at the declaration, rather than at
   * every read site.
   */
  readonly "optional"?: boolean | undefined;
  /**
   * Schema ref (e.g. `"schema:text"`, `"schema:scope"`,
   * `"[schema:scope]"`) or omitted.
   */
  readonly "schema"?: CanonicalSchemaForm | undefined;
  /**
   * Display name, when it must differ from the id. The same field a port
   * carries, for the same reason.
   */
  readonly "title"?: string | undefined;
};

/**
 * A kebab-case slug: lowercase letters/digits separated by single hyphens.
 * 
 * Deserializes permissively (raw string). Validation happens through
 * explicit construction (`Slug::new`, `Slug::new_at`) or the post-decode
 * taxonomy validation pass (`Slug::check`). Custom user slugs are allowed
 * when syntactically valid; no built-in vocabulary table is enforced.
 */
export type CanonicalSlug = string;

/**
 * Kebab-case slug list: accepts scalar-or-array input and normalizes to
 * `Vec<Slug>`.
 * 
 * Always serializes as an array (canonical output). Slug shape validation
 * happens in the post-decode taxonomy pass, not during deserialization, so
 * diagnostics carry canonical field paths.
 */
export type CanonicalSlugList = readonly CanonicalSlug[];

/**
 * Advisory subagent intent metadata.
 */
export type CanonicalSubagentIntent = {
  readonly "allowed-surface"?: readonly string[] | undefined;
  readonly "allowed-tool"?: readonly string[] | undefined;
  readonly "evidence-expectation"?: readonly string[] | undefined;
  readonly "forbidden-model-hint"?: readonly string[] | undefined;
  readonly "forbidden-service-tier-hint"?: readonly string[] | undefined;
  readonly "handoff-expectation"?: readonly string[] | undefined;
  readonly "load-level"?: string | undefined;
  readonly "required-inherited-trait"?: readonly string[] | undefined;
  readonly "role"?: string | undefined;
  readonly "task-boundary"?: string | undefined;
};

/**
 * A `[[relations.suggests]]` entry: advisory influence toward target.
 */
export type CanonicalSuggests = {
  readonly "reason": string;
  /**
   * Suggested target: `trait:*` or `port:*`.
   */
  readonly "target": CanonicalReference;
  readonly "when"?: CanonicalReference | readonly CanonicalReference[] | undefined;
};

/**
 * Optional user-only prose. Defaults to `description` when absent; never
 * rendered to the model.
 */
export type CanonicalSummary = string;

/**
 * A `kind = "terminal"` item's outcome: `flow.success` binds declared
 * output ports and completes the run; `flow.error` writes the reserved
 * error-record port and fails the run.
 */
export type CanonicalTerminalOutcome = "success" | "error";

export type CanonicalWriteOperation = WriteOperation;

/**
 * The canonical trait root aggregate: identity, guidance, activation, ports,
 * slots, schemas, signals, prompts, procedure, composition, and relations.
 */
export type CanonicalTrait = {
  /**
   * Declaration matching declarations. Pure data only; runtime activation is
   * resolved by later gated phases.
   */
  readonly "activation"?: CanonicalDeclaration | undefined;
  /**
   * Declared abstract agent roles for multi-harness procedure routing.
   */
  readonly "agent"?: readonly CanonicalAgent[] | undefined;
  /**
   * Behavior: how the trait should act.
   */
  readonly "behavior"?: CanonicalBehavior | undefined;
  /**
   * Contract contract: conflict declarations and merge policy.
   * Pure data only; runtime composition planning is separate.
   */
  readonly "composition"?: CanonicalContract | undefined;
  /**
   * Named typed conditions (`[condition.<id>]`).
   */
  readonly "condition"?: CanonicalConditionMap | undefined;
  /**
   * Dependencies that this trait references by alias, e.g.
   * `resource:aws/rubric`. Resolution is performed at the IO/check boundary.
   */
  readonly "dependency"?: readonly CanonicalDependency[] | undefined;
  readonly "description": CanonicalDescription;
  /**
   * Product eval declarations: declared checks that can be run.
   */
  readonly "eval"?: readonly CanonicalEval[] | undefined;
  /**
   * Non-standard ctx-specific advisory/reporting extensions.
   */
  readonly "extensions"?: CanonicalExtensions | undefined;
  readonly "id": CanonicalId;
  /**
   * Intent: what the trait requires, focuses on, avoids, and blocks.
   */
  readonly "intent"?: CanonicalIntent | undefined;
  /**
   * Searchable metadata facets. Separate from activation.
   */
  readonly "metadata"?: CanonicalMetadata | undefined;
  readonly "name": CanonicalName;
  /**
   * Port declarations: boundary contracts for trait dataflow.
   */
  readonly "port"?: readonly CanonicalPort[] | undefined;
  /**
   * Optional procedure: deterministic sequence orchestration.
   */
  readonly "procedure"?: CanonicalProcedure | undefined;
  /**
   * Prompt definitions: reusable prompt bodies with optional contracts.
   * Map key is the prompt ID (TOML `[prompt.<id>]`).
   */
  readonly "prompt"?: CanonicalPromptMap | undefined;
  /**
   * Canonical relations: trait-to-trait requires, suggests, and targetless
   * conflicts. Pure data only; graph construction and evaluation are
   * separate deterministic passes.
   */
  readonly "relations"?: CanonicalRelations | undefined;
  /**
   * Resource declarations: opaque blob references for schema bodies and
   * external data.
   */
  readonly "resource"?: readonly CanonicalResource[] | undefined;
  /**
   * Product review scenarios: positive, negative, and edge behavior
   * examples. Not executable test cases.
   */
  readonly "scenario"?: readonly CanonicalScenario[] | undefined;
  /**
   * Local schema declarations: named object schema contracts backed by
   * resource refs or inline fields.
   */
  readonly "schema"?: readonly CanonicalSchemaDeclaration[] | undefined;
  readonly "schema-version": CanonicalSchemaVersion;
  /**
   * Named reusable sequence blocks (`[sequence.<id>]`).
   */
  readonly "sequence"?: CanonicalNamedSequenceMap | undefined;
  /**
   * Declared session identities: named, shareable session bindings that
   * `[[agent]].session` references target.
   */
  readonly "session"?: readonly CanonicalSession[] | undefined;
  /**
   * Setting declarations: typed operator knobs resolved at activation
   * from config layers. Declaration only — resolved values never enter
   * this model.
   */
  readonly "setting"?: readonly CanonicalSetting[] | undefined;
  /**
   * Declared signal identities for procedure sequence emission.
   */
  readonly "signal"?: readonly CanonicalSignal[] | undefined;
  /**
   * Host sink declarations (`[sink.<name>]`): a closed, typed set of
   * trait output the host applies to its own surfaces (task 0110).
   */
  readonly "sink"?: CanonicalSinks | undefined;
  /**
   * Slot definitions: procedure run ledger value contracts.
   */
  readonly "slot"?: readonly CanonicalSlot[] | undefined;
  /**
   * User-only prose; defaults to `description` when absent. Never
   * rendered to the model.
   */
  readonly "summary"?: CanonicalSummary | undefined;
  /**
   * Native family variant identity. This is deliberately absent from 0.2
   * documents, preserving their encoded bytes and digest semantics.
   */
  readonly "variant"?: string | undefined;
  readonly "version": CanonicalSemanticVersion;
};

/**
 * The CDK's pre-synth draft document: `Trait`'s identity fields
 * (`id`, `schema-version`, `version`, `name`, `description`) are optional.
 */
export type CanonicalTraitDraft = {
  /**
   * Declaration matching declarations. Pure data only; runtime activation is
   * resolved by later gated phases.
   */
  readonly "activation"?: CanonicalDeclaration | undefined;
  /**
   * Declared abstract agent roles for multi-harness procedure routing.
   */
  readonly "agent"?: readonly CanonicalAgent[] | undefined;
  /**
   * Behavior: how the trait should act.
   */
  readonly "behavior"?: CanonicalBehavior | undefined;
  /**
   * Contract contract: conflict declarations and merge policy.
   * Pure data only; runtime composition planning is separate.
   */
  readonly "composition"?: CanonicalContract | undefined;
  /**
   * Named typed conditions (`[condition.<id>]`).
   */
  readonly "condition"?: CanonicalConditionMap | undefined;
  /**
   * Dependencies that this trait references by alias, e.g.
   * `resource:aws/rubric`. Resolution is performed at the IO/check boundary.
   */
  readonly "dependency"?: readonly CanonicalDependency[] | undefined;
  readonly "description"?: CanonicalDescription | undefined;
  /**
   * Product eval declarations: declared checks that can be run.
   */
  readonly "eval"?: readonly CanonicalEval[] | undefined;
  /**
   * Non-standard ctx-specific advisory/reporting extensions.
   */
  readonly "extensions"?: CanonicalExtensions | undefined;
  readonly "id"?: CanonicalId | undefined;
  /**
   * Intent: what the trait requires, focuses on, avoids, and blocks.
   */
  readonly "intent"?: CanonicalIntent | undefined;
  /**
   * Searchable metadata facets. Separate from activation.
   */
  readonly "metadata"?: CanonicalMetadata | undefined;
  readonly "name"?: CanonicalName | undefined;
  /**
   * Port declarations: boundary contracts for trait dataflow.
   */
  readonly "port"?: readonly CanonicalPort[] | undefined;
  /**
   * Optional procedure: deterministic sequence orchestration.
   */
  readonly "procedure"?: CanonicalProcedure | undefined;
  /**
   * Prompt definitions: reusable prompt bodies with optional contracts.
   * Map key is the prompt ID (TOML `[prompt.<id>]`).
   */
  readonly "prompt"?: CanonicalPromptMap | undefined;
  /**
   * Canonical relations: trait-to-trait requires, suggests, and targetless
   * conflicts. Pure data only; graph construction and evaluation are
   * separate deterministic passes.
   */
  readonly "relations"?: CanonicalRelations | undefined;
  /**
   * Resource declarations: opaque blob references for schema bodies and
   * external data.
   */
  readonly "resource"?: readonly CanonicalResource[] | undefined;
  /**
   * Product review scenarios: positive, negative, and edge behavior
   * examples. Not executable test cases.
   */
  readonly "scenario"?: readonly CanonicalScenario[] | undefined;
  /**
   * Local schema declarations: named object schema contracts backed by
   * resource refs or inline fields.
   */
  readonly "schema"?: readonly CanonicalSchemaDeclaration[] | undefined;
  readonly "schema-version"?: CanonicalSchemaVersion | undefined;
  /**
   * Named reusable sequence blocks (`[sequence.<id>]`).
   */
  readonly "sequence"?: CanonicalNamedSequenceMap | undefined;
  /**
   * Declared session identities: named, shareable session bindings that
   * `[[agent]].session` references target.
   */
  readonly "session"?: readonly CanonicalSession[] | undefined;
  /**
   * Setting declarations: typed operator knobs resolved at activation
   * from config layers. Declaration only — resolved values never enter
   * this model.
   */
  readonly "setting"?: readonly CanonicalSetting[] | undefined;
  /**
   * Declared signal identities for procedure sequence emission.
   */
  readonly "signal"?: readonly CanonicalSignal[] | undefined;
  /**
   * Host sink declarations (`[sink.<name>]`): a closed, typed set of
   * trait output the host applies to its own surfaces (task 0110).
   */
  readonly "sink"?: CanonicalSinks | undefined;
  /**
   * Slot definitions: procedure run ledger value contracts.
   */
  readonly "slot"?: readonly CanonicalSlot[] | undefined;
  /**
   * User-only prose; defaults to `description` when absent. Never
   * rendered to the model.
   */
  readonly "summary"?: CanonicalSummary | undefined;
  /**
   * Native family variant identity. This is deliberately absent from 0.2
   * documents, preserving their encoded bytes and digest semantics.
   */
  readonly "variant"?: string | undefined;
  readonly "version"?: CanonicalSemanticVersion | undefined;
};

