import { attachProcedureFrom } from "./functional/procedure.js";
import { procedure as procedureBase } from "./procedure.js";

export { agent, oracle, planner, reviewer, searcher, seats, worker } from "./agent.js";
export type {
  AgentFields,
  AgentFunction,
  AgentTemplateFields,
  AgentTemplateFunction,
  AgentTemplateFunctions,
} from "./agent.js";
export { condition } from "./condition.js";
export type {
  ConditionCountFunction,
  ConditionFunction,
  ConditionOutputFunction,
  GuardValue,
  NumericComparisonValue,
} from "./condition.js";
export {
  defineTrait,
  defineVariant,
  effect,
  evaluateTraitFunction,
  flow,
  stage,
  step,
  useBehavior,
  useIntent,
  useResource,
  useVariant,
} from "./functional/index.js";
export type {
  DefineTraitFields,
  DefineVariantFields,
  FieldMatchArms,
  FlowErrorOptions,
  FlowSuccessOptions,
  ForEachRegistrarOptions,
  GuardMatchArms,
  LoopParam,
  ParParam,
  ProcedureFromFields,
  ProcedureFromFunction,
  Stage,
  StageFields,
  TraitFunctionContext,
  UseVariantHandle,
} from "./functional/index.js";
export type {
  AgentModelTier,
  AgentTemplateDefinition,
  AgentTemplateName,
  CdkDiagnostic,
  DirectnessBuiltIn,
  FormatBuiltIn,
  InitiativeBuiltIn,
  IntentAvoidBuiltIn,
  IntentBlockBuiltIn,
  IntentFocusBuiltIn,
  IntentRequireBuiltIn,
  JsonObject,
  JsonValue,
  RefKind,
  RuntimeDelegationPlan,
  RuntimeOperation,
  RuntimeSurface,
  SchemaBuiltin,
  SchemaForm,
  ScopeControlBuiltIn,
  SynthFormat,
  UncertaintyBuiltIn,
  WriteOperation,
} from "./generated.js";
export type {
  CanonicalAgent,
  CanonicalBehavior,
  CanonicalBranchFailureEntry,
  CanonicalBranchFailurePolicy,
  CanonicalChecklistItem,
  CanonicalCommandDeclaration,
  CanonicalCompositionRefList,
  CanonicalCondition,
  CanonicalConditionMap,
  CanonicalConflicts,
  CanonicalContract,
  CanonicalContractRefList,
  CanonicalCtxExtensions,
  CanonicalDeclaration,
  CanonicalDependency,
  CanonicalDigest,
  CanonicalEval,
  CanonicalEvalVariant,
  CanonicalExtensions,
  CanonicalFailureRoute,
  CanonicalFailureTarget,
  CanonicalGuardExpr,
  CanonicalGuardPredicate,
  CanonicalGuidanceItem,
  CanonicalGuidanceItemList,
  CanonicalId,
  CanonicalIntent,
  CanonicalJoinPolicy,
  CanonicalMetadata,
  CanonicalName,
  CanonicalNamedSequence,
  CanonicalNamedSequenceMap,
  CanonicalOutputSink,
  CanonicalOutputSinkList,
  CanonicalPort,
  CanonicalPortDefault,
  CanonicalPortDefaultCommand,
  CanonicalPortDirection,
  CanonicalPredicateList,
  CanonicalProcedure,
  CanonicalProcedureRefList,
  CanonicalProjection,
  CanonicalProjectionSource,
  CanonicalPrompt,
  CanonicalPromptMap,
  CanonicalReference,
  CanonicalRelations,
  CanonicalRelationsRefList,
  CanonicalRequires,
  CanonicalResource,
  CanonicalResourceInputList,
  CanonicalResourceRender,
  CanonicalResourceRoot,
  CanonicalResourceTrigger,
  CanonicalRule,
  CanonicalScenario,
  CanonicalScenarioVariant,
  CanonicalSchemaDeclaration,
  CanonicalSchemaField,
  CanonicalSchemaForm,
  CanonicalSchemaVersion,
  CanonicalSemanticVersion,
  CanonicalSequenceInput,
  CanonicalSequenceInputList,
  CanonicalSequenceItem,
  CanonicalSequenceKind,
  CanonicalSession,
  CanonicalSignal,
  CanonicalSignalEmissionRule,
  CanonicalSlot,
  CanonicalSlug,
  CanonicalSlugList,
  CanonicalSubagentIntent,
  CanonicalSuggests,
  CanonicalSummary,
  CanonicalTrait,
  CanonicalTraitDraft,
  CanonicalWriteOperation,
} from "./generated.js";
export { agentTemplates } from "./generated.js";
export type {
  AgentHandle,
  Brand,
  CheckResultValue,
  ConditionHandle,
  FieldRef,
  GuardHandle,
  Handle,
  InstructionOutputHandle,
  ObjectFieldRefs,
  OptionalSlotRead,
  OutputSinkHandle,
  PortHandle,
  ProcedureHandle,
  PromptHandle,
  PromptTemplate,
  RefHandle,
  ResourceHandle,
  RuleHandle,
  SchemaHandle,
  SchemaRef,
  SequenceHandle,
  SequenceLinearHandle,
  SessionHandle,
  SettingHandle,
  SignalHandle,
  SlotHandle,
  SlotWithFields,
  TraitFamilyHandle,
  TraitHandle,
} from "./handles.js";
export { input } from "./input.js";
export type { CommandInterpolation, CommandTemplateValue, InputFunction, OptionalSlotInputValue } from "./input.js";
export { callout, snippet, steps, table } from "./markdown.js";
export type { CalloutFields, SnippetFields, StepsFields } from "./markdown.js";
export { withHiddenField } from "./meta.js";
export type { CanonicalDeclarationByKind, MetaDeclaration, SourceAnchor, SourceMap } from "./meta.js";
export {
  diagnostics,
  runtimeDelegation,
  synth,
  toDraftJson,
  toDraftJsonWithDiagnostics,
  toDraftJsonWithSourceMap,
} from "./normalize.js";
export type { Draftable, DraftOf, Mutable, SynthPlan } from "./normalize.js";
export { output } from "./output.js";
export type { OutputFunction } from "./output.js";
export { port } from "./port.js";
export type { PortDefaultCommand, PortDirectionHelpers, PortFields, PortFunction } from "./port.js";
export { checklist, dependency, resource, rubric, rule, signal } from "./procedure.js";
export type {
  ChecklistFields,
  DependencyFields,
  DependencyGitSource,
  DependencyLocalSource,
  DependencyNpmSource,
  DependencySource,
  ProcedureFields,
  ResourceFields,
  ResourceFunction,
  RubricFields,
  RuleFields,
  SignalFields,
  SignalFunction,
} from "./procedure.js";
/** The object-layer `procedure(...)` builder, augmented with `procedure.from(fields, body)` (0106) — one exported symbol, both call shapes. */
export const procedure = attachProcedureFrom(procedureBase);
export { prompt } from "./prompt.js";
export type { PromptFields, PromptFunction, PromptInterpolation } from "./prompt.js";
export { ref } from "./ref.js";
export type { RefFunction, RefText } from "./ref.js";
export { ctxSchemaResource, schema } from "./schema.js";
export type {
  SchemaEnumSpec,
  SchemaFieldFields,
  SchemaFieldRecord,
  SchemaFunction,
  SchemaObjectField,
  SchemaObjectFields,
  SchemaObjectHandle,
  SchemaObjectValue,
  SchemaTemplateFunction,
  SchemaUnionHandle,
  SchemaValue,
} from "./schema.js";
export { idFromTitle, sequence } from "./sequence.js";
export type {
  ArgvItem,
  BranchSequenceFields,
  CheckSequenceFields,
  CommandSequenceFields,
  ExhaustionPolicy,
  FailureRoute,
  ForEachSequenceFields,
  GateOptions,
  LoopSequenceFields,
  ParallelBranchFailureEntry,
  ParallelBranchFailurePolicy,
  ParallelJoinOption,
  ParallelOptions,
  ParallelSequenceFields,
  ProjectProjection,
  ProjectSequenceFields,
  TerminalBinding,
  TerminalSequenceFields,
  PromptRegistrarOptions,
  SequenceFields,
  SequenceFunction,
  SequenceInputValue,
  SequenceOutputValue,
} from "./sequence.js";
export type { SignalVerb, SignalVerbName } from "./signal-verb.js";
export { session } from "./session.js";
export type { SessionBinding, SessionFunction, SessionLifecycle, SessionOptions } from "./session.js";
export type { SessionTitleSinkInput, SinkFields } from "./sink.js";
export { operation, slot } from "./slot.js";
export type { LiteralProjectionSource, OperationFunction, SlotFields, SlotFunction } from "./slot.js";
export {
  directness,
  format,
  initiative,
  intent,
  method,
  scopeControl,
  tone,
  trait,
  uncertainty,
  verbosity,
} from "./trait.js";
export type {
  Behavior,
  BehaviorFields,
  CustomSlug,
  GuidanceInput,
  GuidanceItem,
  Intent,
  IntentBuiltIn,
  IntentSpec,
  MethodBuiltIn,
  SchemaVersion,
  SemVer,
  Slug,
  ToneBuiltIn,
  TraitFields,
  TraitMetadata,
  VerbosityBuiltIn,
} from "./trait.js";
export { isTraitFamilyHandle, NATIVE_VARIANT_SCHEMA_VERSION, resolveTraitFamily, variant } from "./variant.js";
export type {
  FamilyEnvelope,
  FlattenedVariant,
  ResolvedFamilyVariant,
  TraitFamilyMap,
  VariantFields,
  VariantHandle,
  VariantImportHandle,
  VariantLeafHandle,
  VariantTopologyNode,
} from "./variant.js";
