//! `ctx traits help --json` (P453): a full, parser-derived report of the
//! command surface — visible and hidden names, release groups, one-line
//! descriptions, aliases, flags, and nested subcommands — generated by
//! walking Clap's own command tree rather than maintaining a second,
//! hand-copied inventory that could silently drift from `TraitsCommand`.

use ctx_traits_core::response::CommandOutput;

use crate::app::command_handlers::print_json_report;
use crate::app::surface::cli;

#[derive(serde::Serialize)]
#[serde(rename_all = "kebab-case")]
struct SurfaceFlag {
    name: String,
    long: Option<String>,
    short: Option<String>,
    hidden: bool,
}

#[derive(serde::Serialize)]
#[serde(rename_all = "kebab-case")]
struct SurfaceCommand {
    name: String,
    /// Release group (see [`GROUPS`]/[`classify`]), present only for the
    /// top-level `ctx traits <command>` verbs `TRAITS_HELP` groups; nested
    /// subcommands (e.g. `trust verify`, `cache prune`) report `None` since
    /// grouping is a top-level release-screen concept only.
    group: Option<&'static str>,
    hidden: bool,
    about: Option<String>,
    aliases: Vec<String>,
    flags: Vec<SurfaceFlag>,
    subcommands: Vec<SurfaceCommand>,
}

#[derive(serde::Serialize)]
#[serde(rename_all = "kebab-case")]
struct SurfaceReport {
    tagline: &'static str,
    commands: Vec<SurfaceCommand>,
}

/// Every release group `ctx traits -h` shows, in display order, plus the
/// catch-all `hidden` bucket for every command intentionally left off that
/// screen. Kept deliberately small and exhaustive: [`classify`] refuses to
/// generate a report for a command absent from this table, so a newly added
/// `TraitsCommand` variant cannot silently go unclassified.
const GROUPS: &[&str] = &[
    "core",
    "author",
    "manage",
    "ai-assistance",
    "execute",
    "hidden",
];

/// Classify one `ctx traits` subcommand name (Clap's kebab-case rendering of
/// the `TraitsCommand` variant) into its release group. Every visible
/// command in `TRAITS_HELP` appears here under its real group; every other
/// currently-defined command — including compatibility aliases' canonical
/// name, which is classified once under its canonical spelling — is `hidden`.
/// Any name not covered here is a generation error rather than a silently
/// dropped row.
fn classify(name: &str) -> Result<&'static str, String> {
    let group = match name {
        // The 2026-08-18 regroup: five release groups (core / author /
        // manage / ai-assistance / execute); everything else — including
        // former release commands
        // `export`/`host`/`migrate`/`activate`/`explain`/`config`/`task`,
        // which stay runnable — is `hidden`.
        "init" | "doctor" | "cache" => "core",
        "build" | "create" | "import" => "author",
        "list" | "check" | "trust" | "dependency" | "diff" => "manage",
        "generate" | "refine" | "critique" => "ai-assistance",
        "run" | "merge" => "execute",
        // P567: `vendor`/`install`/`remove`/`update`/`outdated`/`info` are
        // hidden aliases under `dependency`; they stay classified so the
        // hidden-command help path keeps working for the deprecation window.
        "vendor" | "install" | "remove" | "update" | "outdated" | "info" | "publish"
        | "export" | "host" | "migrate" | "activate" | "review" | "config" | "task" | "explain"
        | "claim-gate" | "hygiene" | "cost" | "prepare-public" | "context-contracts" | "policy"
        | "evidence" | "compatibility" | "subagent" | "inspect" | "manifest" | "schema"
        | "sdk-generate" | "synth" | "generate-evals" | "import-refresh" | "run-info"
        | "session" | "mcp" | "drive" | "call" | "run-status" | "run-frame" | "next" | "set"
        | "deactivate" | "deprecate" | "eval" | "prompt" | "preview" | "search" | "resolve"
        | "pack" | "context" | "hook" | "help" | "stats" | "story" | "tui-demo" | "edit"
        | "running" => "hidden",
        other => {
            return Err(format!(
                "ctx traits help --json: unclassified command {other:?}; add it to the release-group classification in help_surface.rs"
            ));
        }
    };
    debug_assert!(GROUPS.contains(&group));
    Ok(group)
}

fn build_flags(command: &clap::Command) -> Vec<SurfaceFlag> {
    let mut flags: Vec<SurfaceFlag> = command
        .get_arguments()
        .filter(|arg| !arg.is_positional())
        .map(|arg| SurfaceFlag {
            name: arg.get_id().to_string(),
            long: arg.get_long().map(|s| s.to_string()),
            short: arg.get_short().map(|c| c.to_string()),
            hidden: arg.is_hide_set(),
        })
        .collect();
    flags.sort_by(|a, b| a.name.cmp(&b.name));
    flags
}

/// Build one command's report row. `top_level` is true only for the direct
/// `ctx traits <command>` children walked from [`build_report`]: only those
/// go through [`classify`] and can fail generation over an unclassified
/// name — a command's own nested subcommands (`trust verify`, `cache
/// prune`, ...) are structural detail, not additional release-group rows.
fn build_command(command: &clap::Command, top_level: bool) -> Result<SurfaceCommand, String> {
    let name = command.get_name().to_string();
    let group = if top_level {
        Some(classify(&name)?)
    } else {
        None
    };
    let mut aliases: Vec<String> = command.get_all_aliases().map(|a| a.to_string()).collect();
    aliases.sort();
    let mut subcommands = Vec::new();
    for sub in command.get_subcommands() {
        subcommands.push(build_command(sub, false)?);
    }
    subcommands.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(SurfaceCommand {
        name,
        group,
        hidden: command.is_hide_set(),
        about: command.get_about().map(|s| s.to_string()),
        aliases,
        flags: build_flags(command),
        subcommands,
    })
}

fn build_report() -> Result<SurfaceReport, String> {
    let root = cli::command();
    let traits_command = root
        .find_subcommand("traits")
        .ok_or_else(|| "ctx traits help --json: parser tree has no `traits` command".to_string())?;
    let mut commands = Vec::new();
    for sub in traits_command.get_subcommands() {
        commands.push(build_command(sub, true)?);
    }
    commands.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(SurfaceReport {
        tagline: cli::TRAITS_TAGLINE,
        commands,
    })
}

pub(crate) fn handle_help(json: bool) -> crate::Result<CommandOutput<()>> {
    if !json {
        cli::print_traits_help();
        return Ok(CommandOutput::new(()));
    }
    let report = build_report().map_err(|message| crate::Error::Command { message })?;
    print_json_report(&report, "help output")?;
    Ok(CommandOutput::new(()))
}
